### ISSUE TITLE
Variable assignment and usage during -x for parameter substitution

### ISSUE THREAD

**Issue by theherk** [sharkdp/fd#1084]
**What version of `fd` are you using?**
8.4.0

I'm concerned this may have been asked and answered, but I can't sort out if this is possible or how it is done.

Consider a direction containing:

```
ᐅ exa -T
.
└── config
   ├── a.toml
   └── b.toml
```

`echo` alone works as expected:

```
ᐅ fd .toml config -x echo
config/b.toml
config/a.toml
```

But this does not:

```
ᐅ fd .toml config -x c={} echo $c
[fd error]: Command not found: Command { inner: "c=config/b.toml" "echo", remaining_argument_length: 1040030 }
[fd error]: Command not found: Command { inner: "c=config/a.toml" "echo", remaining_argument_length: 1040030 }
```

What I aim to do is something like:

```
ᐅ fd .toml config -x c={} echo ${c/fig/cur}
```

Is it possible to set a variable, in-line per invocation?

**Comment by tavianator** [comment]
First of all, `c=config/a.toml echo $c` is shell syntax.  `fd` doesn't execute a shell by default, instead it directly executes the program you ask for.  But if you as for the shell explicitly, it will work.

Secondly, the exact syntax you gave doesn't work even in the shell:

```console
tavianator@graviton $ c=config/a.toml echo $c

tavianator@graviton $
```

But it does work as two separate commands:

```console
tavianator@graviton $ c=config/a.toml
tavianator@graviton $ echo $c
config/a.toml
```

We can run one or more shell commands with `sh -c "<command>; <command>..."`, so let's tell `fd` to do that:

```console
tavianator@graviton $ fd .toml config -x sh -c 'c={}; echo $c'
config/b.toml
config/a.toml
```

That worked, but it's vulnerable to command injection:

```console
tavianator@graviton $ touch "config/; figlet Hello world; : .toml"
tavianator@graviton $ fd .toml config -x sh -c 'c={}; echo $c'
config/a.toml
config/b.toml
 _   _      _ _                            _     _ 
| | | | ___| | | ___   __      _____  _ __| | __| |
| |_| |/ _ \ | |/ _ \  \ \ /\ / / _ \| '__| |/ _` |
|  _  |  __/ | | (_) |  \ V  V / (_) | |  | | (_| |
|_| |_|\___|_|_|\___/    \_/\_/ \___/|_|  |_|\__,_|
                                                   
config/
```

We can fix that with proper quoting and passing the path as an argument to the shell instead of interpolating it into the string:

```console
$ fd .toml config -x sh -c 'c="$1"; echo "$c"' sh
config/; figlet Hello world; : .toml
config/a.toml
config/b.toml
```

**Comment by theherk** [comment]
I missed the `;` by accident but I had tried a very similar command:

```
ᐅ fd toml config -x sh -c "c={}; echo $c"
```

which does work. But it does with single quotes as you illustrate:

```
ᐅ fd toml config -x sh -c 'c={}; echo $c'
config/a.toml
config/b.toml
```

Thank you very much for the detailed help.
