### ISSUE TITLE
Should --max-results=1 and piping through head -1 return the same result?

### ISSUE THREAD

**Issue by d0e8414e** [sharkdp/fd#1099]
**What version of `fd` are you using?**
`$ /usr/bin/fdfind --version`
`fd 8.3.1`

I am trying to find the "top" (sorted numerically/standard ls order) sub-directory under some other directory.  fd(find) with max-results=1 seems to return a random result.  Piping through head -1 returns what I'm expecting.  I read through some of the max-results stuff and since it looks to be a replacement to piping through head -1, I assume it should return the same thing as head . . . ?

Directory in question:
```
$ ls -l ~/tmp/_top
total 44
drwxrwxr-x 2 d0e8414e d0e8414e 4096 Sep  1 13:09 8338034491
drwxrwxr-x 2 d0e8414e d0e8414e 4096 Aug 31 12:57 8338034962
drwxrwxr-x 2 d0e8414e d0e8414e 4096 Aug 29 12:28 8338209475
drwxrwxr-x 2 d0e8414e d0e8414e 4096 Aug 29 10:19 8338217353
drwxrwxr-x 2 d0e8414e d0e8414e 4096 Aug 26 16:50 8338632766
drwxrwxr-x 2 d0e8414e d0e8414e 4096 Aug 16 11:30 8339336163
drwxrwxr-x 2 d0e8414e d0e8414e 4096 Aug  4 13:58 8340883023
drwxrwxr-x 2 d0e8414e d0e8414e 4096 Jul  8 13:36 8342698330
drwxrwxr-x 2 d0e8414e d0e8414e 4096 Jul  1 15:13 8343297237
drwxrwxr-x 2 d0e8414e d0e8414e 4096 Jun 24 16:00 8343899564
drwxrwxr-x 2 d0e8414e d0e8414e 4096 Jun 23 11:06 8344003239
```

Piping through head:
`$ /usr/bin/fdfind --full-path /home/d0e8414e/tmp/_top -t d -a --exact-depth=3 | head -1
`
Returns:
`/home/d0e8414e/tmp/_top/8338034491`

fd with --max-results returns seemingly random results:
```
$ /usr/bin/fdfind --full-path /home/d0e8414e/tmp/_top -t d -a --exact-depth=3 --max-results=1
/home/d0e8414e/tmp/_top/8338034962

$ /usr/bin/fdfind --full-path /home/d0e8414e/tmp/_top -t d -a --exact-depth=3 --max-results=1
/home/d0e8414e/tmp/_top/8343899564

$ /usr/bin/fdfind --full-path /home/d0e8414e/tmp/_top -t d -a --exact-depth=3 --max-results=1
/home/d0e8414e/tmp/_top/8338217353

```
...etc...

Is this expected behavior?

Thanks!

**Comment by sharkdp** [comment]
> Is this expected behavior?

Yes. Due to its parallelized nature, `fd`s output order is inherently non-deterministic. But note that you should *never* rely on filesystem traversal order, even in single-threaded programs. If you need sorted output, do so explicitly. That being said, you *can* try to use `--threads=1`/`-j1` to limit `fd` to one thread... and you should probably get a somewhat more stable result. But I don't recommend you rely on that being deterministic.

> Piping through head -1 returns what I'm expecting

Yes, probably because your directory is small and `fd` finishes fast. In that case, it will sort the results for you. But this does not work for larger directories. Again, if you want the first result in alphabetical order, you need to `sort` explicitly (`fd … | sort | head -1`). This will be much slower than `fd -1 …`, but rightfully so. There is no guarantee that the filesystem will give you the "first-in-alphabetical-order" file first in a traversal.

> standard ls order

`ls` sorts alphabetically by default. Use `ls -U` to see the unsorted result.

**Comment by d0e8414e** [comment]
Ah, like a sql select - can't assume order.  Makes sense.  Thanks for the detailed explanation.  I've enjoyed using your (all contributors!) tools for the past few months or so.

**Comment by sharkdp** [comment]
Thank you for your feedback!
