### ISSUE TITLE
Fix flaky `--full-path` unit tests

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/fd#1181]
### Describe the bug you encountered:

Some of our `--full-path` unit tests are non-deterministic and can fail.

The reason is that `--full-path` searches the full *absolute* path. This can lead to additional `fd` matches if (by chance) the *temporary directory name contains one of the search patterns*. For example, in [this CI run](https://github.com/sharkdp/fd/actions/runs/3517827315/jobs/5896045947), the `test_and_plus_full_path` unit test failed with an additional unexpected match (`one/two/three/d.foo`), even though it only contains two of the three search patterns of the `fd three --full-path --and foo --and dir` call.

I was able to reproduce this locally after running the test thousands of times (the odds are 1 : 3000). The test fails if the temporary directory name contains a *dir* substring (case insensitive):

![image](https://user-images.githubusercontent.com/4209276/203163147-c189bfa2-eaaf-4c62-8339-02b59634b594.png)

### Describe what you expected to happen:

All unit tests should be deterministic. When we fix this, we should go through all `--full-path` tests and find a good strategy to avoid this kind of "vulnerability".

### What version of `fd` are you using?

c9d39684758d0d898082370d5c5fe7e8aef3a385

### Which operating system / distribution are you on?

Linux. I'm sure this can similarly fail on other operating systems as well.

@Uthar FYI

**Comment by Ptipiak** [comment]
The library tempdir is not maintained and the github repository as been archive: https://github.com/rust-lang-deprecated/tempdir
The library should be replaced with a new maintained one with support to non-clashing directory names ?
Or the random tempory directory generation could be taken internaly by `fd` to make sure it fullfills it's need ?

**Comment by tmccombs** [comment]
@Ptipiak I've replaced tempdir with tempfile (it's recommended replacement). 

It would be possible to avoid this issue by using https://docs.rs/tempfile/latest/tempfile/struct.Builder.html#method.rand_bytes to specify using only 2 random "bytes", so that the random sequence will never match the patterns we use (which are all three or more characters). I'm not sure if that is the best approach. 

I think that 2 random bytes is probably enough, since 2 alphanumeric characters has 1296 possibilities, so if we had 12 test running concurrently, there would be a ~1% chance of collision. And in the collision it will retry. So I _think_ we would only run into problems if we had 1256 tests running at the same time, which would be pretty crazy.
