### ISSUE TITLE
--exec changes order of results

### ISSUE THREAD

**Issue by dvogel** [sharkdp/fd#1228]
### Checks

- [X] I have read the troubleshooting section and still think this is a bug.

### Describe the bug you encountered:

```
$ for x in `seq 100`; do touch $(cat /dev/urandom | tr -d -C 'A-Za-z' | head -c1); done
$ ls
a  A  B  c  C  d  D  e  f  F  G  i  I  j  k  K  L  m  M  n  N  o  O  p  P  q  Q  r  R  s  S  t  T  u  U  v  V  w  W  x  X  y  Y  z
$ fd -j1 -t f
A
B
C
D
F
G
I
K
L
M
N
O
P
Q
R
S
T
U
V
W
X
Y
a
c
d
e
f
i
j
k
m
n
o
p
q
r
s
t
u
v
w
x
y
z
$ fd -j1 -t f -x ls -1
./B
./V
./p
./n
./z
./s
./D
./P
./u
./d
./R
./G
./X
./Y
./t
./i
./j
./F
./M
./U
./f
./Q
./e
./r
./O
./q
./T
./A
./K
./I
./c
./C
./N
./W
./w
./v
./y
./k
./L
./m
./x
./S
./o
./a
```

### Describe what you expected to happen:

I would expect these commands to output the same files in the same order:

```
fd -j1 -t f
```

```
fd -j1 -t f -x ls -1
```

The `./` prefix is fine. It is the order that seems like a bug to me.

### What version of `fd` are you using?

8.3.0 and 8.6.0

### Which operating system / distribution are you on?

```shell
$ uname -srm
Linux 6.0.0-1009-oem x86_64
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
```
```

**Comment by tmccombs** [comment]
Here is why I think you are seeing the results in the order you do for each command:

`ls`: is sorting the results alphabetically (and mostly case insensitve, unless the names differ only in case).
`fd -j 1`: Since there are less than 1000 results, and they are returned fairly quickly, the results are sorted before printing (but case sensitively)
`fd -j 1 -x ls`: Is not doing any sorting. Since you have a single thread, the commands are run in the order that they are returned by the file system.

**Comment by dvogel** [comment]
>  fd -j 1: Since there are less than 1000 results, and they are returned fairly quickly, the results are sorted before printing (but case sensitively)

@tmccombs is this the expected sorting behavior? The output is sorted but only if there are less than 1000 results? That certainly seems inline with these slightly different repro steps:

```
$ for x in `seq 2000`; do touch $(cat /dev/urandom | tr -d -C 'A-Za-z' | head -c3); done
$ ls -1 | tail 
ZXT
Zxy
zYa
Zyf
zyh
zYO
ZZM
zZn
zZq
Zzx
$ fd -j1 -t f | tail
Zzx
ZMN
qnT
oOY
noN
Dbz
qsA
kPm
haa
IXO
$ fd -j1 -t f -x ls -1 | tail
./Zzx
./ZMN
./qnT
./oOY
./noN
./Dbz
./qsA
./kPm
./haa
./IXO
```

Why does the same sorting logic not apply to the order the results are fed into `-x`?

I wasn't able to find any `--help` or README content explaining the sorting. I was inferring from all of the results I had seen that the output was always sorted. A note on the `-x` option or an option to completely disable the sorting (which would seemingly make both commands have the same unordered output) could clarify the situation.

**Comment by tmccombs** [comment]
> @tmccombs is this the expected sorting behavior? The output is sorted but only if there are less than 1000 results? That certainly seems inline with these slightly different repro steps:

Yes, that is intentional. I believe that was for performance reasons, and so that you can start getting results quickly instead of having to wait for all results before you can finish sorting.  But if you have a small number of results, you can still have the convenience of sorted results.

 
> Why does the same sorting logic not apply to the order the results are fed into `-x`?

I'm not sure if that is intentional or not. 

> I wasn't able to find any `--help` or README content explaining the sorting. I was inferring from all of the results I had seen that the output was always sorted. A note on the `-x` option or an option to completely disable the sorting (which would seemingly make both commands have the same unordered output) could clarify the situation.

I couldn't find any documentation on that either.

**Comment by sharkdp** [comment]
> The output is sorted but only if there are less than 1000 results?

That is not the (only) criterion. It also depends on how fast results come in. The idea is the following: for very long searches, we certainly want to show results to the user in a streaming way, i.e. we want to directly show them on the terminal as soon as they are found. This means we can not show them in any deterministic order (sorted). However, `fd` has a feature (which we added because we thought it *improves* UX) where, if the search has finished very fast (in under 100 ms), we will sort all results first before printing. This means that `fd` will be in a buffering mode during those first 100 ms. It will not print anything to the console, unless the *number* of search results exceeds a certain threshold (1000). The two constants are defined here:

https://github.com/sharkdp/fd/blob/ab7d5eff874073bc6f09800614889c3a2b7a891d/src/walk.rs#L45-L48

> Why does the same sorting logic not apply to the order the results are fed into `-x`?

Since the method above is *not* deterministic (the search could take 105 ms the first time and 95 ms the second time - which would change the output order; also, of course, something could change in the filesystem), we don't want users to *ever* rely on output order.

As for why the feature above is not implemented for `fd -x`: I think that's mostly because we thought that feature is only interesting if someone looks at the search results.

> I wasn't able to find any `--help` or README content explaining the sorting. I was inferring from all of the results I had seen that the output was always sorted

This should definitely be improved!

> A note on the `-x` option or an option to completely disable the sorting (which would seemingly make both commands have the same unordered output) could clarify the situation.

I'd rather not add that option. Because even with that option, output order can always change. If you need a deterministic order, I suggest to use sth like

```
fd --print0 | sort --zero-terminated | xargs --null -L1 …
```

**Comment by tavianator** [comment]
Yet another example of Hyrum's law :).  Maybe we should change

https://github.com/sharkdp/fd/blob/ab7d5eff874073bc6f09800614889c3a2b7a891d/src/walk.rs#L311

to

```rust
self.buffer.shuffle(&mut thread_rng());
```

;)

**Comment by sergeevabc** [comment]
I encountered incorrect sorting when calculating hashes.

``` console
$ ver && fd --version
Microsoft Windows [Version 6.1.7601]
fd 10.2.0

$ fd -e txt -x xxhsum
1f2053563c8192c9  ./птицы.txt
bdff894bce845021  ./птицы-vögel-pájaros-birds.txt
31bc040393748d50  ./vögel.txt
d3221511079b48e3  ./pájaros.txt
be207dcd8b9bd84c  ./birds.txt

$ fd -e txt -j 1 -x xxhsum
1f2053563c8192c9  ./птицы.txt
bdff894bce845021  ./птицы-vögel-pájaros-birds.txt
31bc040393748d50  ./vögel.txt
d3221511079b48e3  ./pájaros.txt
be207dcd8b9bd84c  ./birds.txt
```

Whereas reference (expected) sort order is

``` console
$ xxhsum *.txt

be207dcd8b9bd84c  birds.txt
d3221511079b48e3  pájaros.txt
31bc040393748d50  vögel.txt
bdff894bce845021  птицы-vögel-pájaros-birds.txt
1f2053563c8192c9  птицы.txt

$ zpaqfranz hash *.txt -sha256 -pakka
ccf45b44c83bcc337e26321aa1491606990f8fecc43048f2dfd7f06b9d828473 birds.txt
7f36bc0c42daf8e2a91ef9565b0ecd23e6691bc7e2eb07a6097c93bb8c2327f3 pájaros.txt
31a51f37aa52fc8687a8ec33f0de0573a64134044abb74d14e92713ae8ee6227 vögel.txt
fff9c09f2a3df7df67c1b0fe5e3758265bbf4f053135759a0a6fb2c891302df2 птицы-vögel-pájaros-birds.txt
63f9f5c3830d362d77bcc916fb995c35c92810488edcdd21d36c11f52488c6ae птицы.txt

$ rhash --sha256 *.txt
ccf45b44c83bcc337e26321aa1491606990f8fecc43048f2dfd7f06b9d828473  birds.txt
7f36bc0c42daf8e2a91ef9565b0ecd23e6691bc7e2eb07a6097c93bb8c2327f3  pájaros.txt
31a51f37aa52fc8687a8ec33f0de0573a64134044abb74d14e92713ae8ee6227  vögel.txt
fff9c09f2a3df7df67c1b0fe5e3758265bbf4f053135759a0a6fb2c891302df2  птицы-vögel-pájaros-birds.txt
63f9f5c3830d362d77bcc916fb995c35c92810488edcdd21d36c11f52488c6ae  птицы.txt

$ filehash --sha256 -i -d . *.txt
ccf45b44c83bcc337e26321aa1491606990f8fecc43048f2dfd7f06b9d828473 birds.txt
7f36bc0c42daf8e2a91ef9565b0ecd23e6691bc7e2eb07a6097c93bb8c2327f3 pájaros.txt
31a51f37aa52fc8687a8ec33f0de0573a64134044abb74d14e92713ae8ee6227 vögel.txt
fff9c09f2a3df7df67c1b0fe5e3758265bbf4f053135759a0a6fb2c891302df2 птицы-vögel-pájaros-birds.txt
63f9f5c3830d362d77bcc916fb995c35c92810488edcdd21d36c11f52488c6ae птицы.txt

$ sha256deep -b *.txt
ccf45b44c83bcc337e26321aa1491606990f8fecc43048f2dfd7f06b9d828473  birds.txt
7f36bc0c42daf8e2a91ef9565b0ecd23e6691bc7e2eb07a6097c93bb8c2327f3  pájaros.txt
31a51f37aa52fc8687a8ec33f0de0573a64134044abb74d14e92713ae8ee6227  vögel.txt
fff9c09f2a3df7df67c1b0fe5e3758265bbf4f053135759a0a6fb2c891302df2  птицы-vögel-pájaros-birds.txt
63f9f5c3830d362d77bcc916fb995c35c92810488edcdd21d36c11f52488c6ae  птицы.txt

$ coreutils sha256sum *.txt
ccf45b44c83bcc337e26321aa1491606990f8fecc43048f2dfd7f06b9d828473 *birds.txt
7f36bc0c42daf8e2a91ef9565b0ecd23e6691bc7e2eb07a6097c93bb8c2327f3 *pájaros.txt
31a51f37aa52fc8687a8ec33f0de0573a64134044abb74d14e92713ae8ee6227 *vögel.txt
fff9c09f2a3df7df67c1b0fe5e3758265bbf4f053135759a0a6fb2c891302df2 *птицы-vögel-pájaros-birds.txt
63f9f5c3830d362d77bcc916fb995c35c92810488edcdd21d36c11f52488c6ae *птицы.txt
```

**Comment by tavianator** [comment]
@sergeevabc This is expected, fd provides no guarantees of any particular order.  Frequently, the order will even change between multiple runs.  If you need sorted results with `-x` you can do something like

```console
$ fd -e txt -0 | sort -z | xargs -0 -n1 sha256sum
```

**Comment by sergeevabc** [comment]
@tavianator, I guess it is expected by developers, but certainly not by users. The app should not be like some quantum black box which output is one today and another tomorrow, it should be as predictable as possible, excluding unauthorized deviation. Imagine that you asked an app to extract a file from an archive, but it unpacked your file and some random file as well because, well, it is raining outside. Looks like downgrade from `find`. Compare

``` console
$ fd -e txt -x xxhsum
1f2053563c8192c9  ./птицы.txt
bdff894bce845021  ./птицы-vögel-pájaros-birds.txt
31bc040393748d50  ./vögel.txt
d3221511079b48e3  ./pájaros.txt
be207dcd8b9bd84c  ./birds.txt

$ find.exe *.txt -exec xxhsum {} ;
be207dcd8b9bd84c  birds.txt
d3221511079b48e3  pájaros.txt
31bc040393748d50  vögel.txt
bdff894bce845021  птицы-vögel-pájaros-birds.txt
1f2053563c8192c9  птицы.txt
```
