### ISSUE TITLE
Recommended way to sort results

### ISSUE THREAD

**Issue by flip111** [sharkdp/fd#196]
Before with `find` i could use the `printf` option https://unix.stackexchange.com/a/29901/196971

what the best way to solve this with fd ?

**Comment by sharkdp** [comment]
What about using `xargs`?

``` bash
> fd -0 foo | xargs -0 ls -ltr
```

**Comment by flip111** [comment]
It works .. so i will close this issue. It would be nice to have a sorting flag that keeps coloring in the output. Or alternatively a flag to execute a command for all the results (`fd -X "ls -ltr" foo path`).

**Comment by rien333** [comment]
@sharkdp Is that still the recommended way? Something like `fd -e pdf -X ls -t` seems to work just as fine as the `xargs` equivalent.

**Comment by sharkdp** [comment]
@rien333 You are right. I would now recommend to use the `-X` option, simply because it is easier to type :+1:

**Comment by sharkdp** [comment]
There is a new way to do this now: With #556 implemented, you can simply use `fd -l` to run `ls -l` in the background:

This is now supported (in a particular way) by the new `-l`/`--list-details` option, see #556.
![image](https://user-images.githubusercontent.com/4209276/78337992-3e5a4600-7592-11ea-9c3b-63145dfd2835.png)

**Comment by sharkdp** [comment]
This has now been released in [fd v8.0](https://github.com/sharkdp/fd/releases/tag/v8.0.0).

**Comment by sergeevabc** [comment]
> This is now supported (in a particular way) by the new `-l`/`--list-details` option, see #556.

``` console
$ fd -l
[fd error]: 'fd --list-details' is not supported on Windows unless GNU 'ls' is installed.
```
Fail.

Still looking for a native way to sort the output in alphabetical order.
Damn, people, what's wrong with implementing [much requested](https://github.com/sharkdp/fd/issues/789) --sort flag?

**Comment by rien333** [comment]
What's wrong with installing GNU's ls? If a system can acquire and install `fd`, wouldn't it be fairly easy to also install some GNU (compatible) tools?

**Comment by sergeevabc** [comment]
@rien333, yeah, then let's refuse to build the app for other platforms at all, saying that once user is able to download this app, then why not install the whole Unix zoo as well. After all, it's free, it's easy peasy lemon squeezy, it means less troubleshooting and more time for developing new features. Hooray, my eye.

Do you know what portability means? I mentioned `-l` flag as a poorly done job: the flag is there, but it doesn't do any good out of the box. How about making a player and then require users to surf the Internet in search of libraries for desired formats? To hell with this modularity in a self-contained utility consisting of a single file. And most importantly `ls` is not a solution to the sorting problem, it's an [attention theft](https://en.wikipedia.org/wiki/Attention_economy), whereas human attention is a scarce commodity.

``` console
$ fd -H -g "_startup" -l
-rwxrwxrwx 1 somebody somegroup 0 Jan  7 10:03 '.\Autohotkey\_startup'
-rwxrwxrwx 1 somebody somegroup 0 Jan  7 05:28 '.\DNSCrypt\_startup'
-rwxrwxrwx 1 somebody somegroup 0 Jan  7 05:28 '.\Keepass\_startup'
```
What rights-somebody-somegroup under Windows? What's wrong with timestamps?
I need a list of paths in alphabetical order, nothing more.

``` console
$ fd -H -g "_startup" --sort
Autohotkey\_startup
DNSCrypt\_startup
Keepass\_startup
```

Since search results are paths, then it's crucial to provide obvious ways to output these paths. Just like `base64` allows you not only to encode and decode, but to set the column width, like `du` allows you to measure sizes using powers of 1000 besides 1024, and `ImageMagick` allows you to select color format other than RGB (HEX, HSL…).

**Comment by rien333** [comment]
>  I mentioned -l flag as a poorly done job: ...  I need a list of paths in alphabetical order, nothing more.

I do not think you have explained the connection between `-l` and sorting, actually? 

> then why not install the whole Unix zoo as well.

If your OS has no way to the sort/filter lines of output, then this is not even that bad of an idea, especially because that "zoo" of extremely portable utilities is just 16MB in size.  My guess, however, is that windows does already have such text manipulation capabilities, making `fd` usable out of the box on common operating systems.

**Comment by tmccombs** [comment]
> I mentioned -l flag as a poorly done job: the flag is there, but it doesn't do any good out of the box

The `-l` option is basically an alias for `-X ls -l -h -d` 

If you don't have `ls` installed, there isn't much it can do. 

Maybe there is some roughly equivalent powershell command it could run instead? But then the output would be very different on windows than other platforms, and would either be different depending on whether you had GNU ls installed, or would never be consistent with other environments (if we always used a powershell command). 

> And most importantly ls is not a solution to the sorting problem, it's an [attention theft](https://en.wikipedia.org/wiki/Attention_economy), whereas human attention is a scarce commodity. Just look at this mess:

I think the discussion of the `-l` option has confused you a little bit. The relevance of `-l` to sorting is not that it sorts the output, but that it will output additional fields which can be used by another command to sort by (for example the mtime). 

> I need a list of paths in alphabetical order, nothing more.

So in your case, assuming that since you are on windows, you are using powershell, you can just pipe the output to [`Sort-Object`](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/sort-object?view=powershell-7.4).

> what's wrong with implementing https://github.com/sharkdp/fd/issues/324 https://github.com/sharkdp/fd/issues/789 --sort flag?

It doesn't really add much value over composing fd with existing tools (depending on your operating system) to sort the output.

**Comment by tmccombs** [comment]
Have you read the unix stackexchange link from the OP? Despite the title, the original request for this issue was how to do the equivalent of

```bash
find . your-options -printf "%T+ %p\n" | sort
```

and note that that still uses sort.

The relevance of `-l` is that currently, one way to accomplish that with fd would be that the `-l` output includes the date, which could be used as a sorting field. Although, it isn't in a format that is very sortable, so I think `-X ls -t` would still be a better way to accomplish that.

And yes it does rely on a unix-specific tool. But there probably is a way to do tthe same on windows as well, but I'm not familiar enough with windows to know what that is.

**Comment by flip111** [comment]
> Have you read the unix stackexchange link from the OP?

I am the Original Poster. The stackexchange post was as an example of the kind of functionality i wanted (the outcome) not a specific request to do something with flags and/or pipes.

> Although, it isn't in a format that is very sortable, so I think `-X ls -t` would still be a better way to accomplish that.

I agree with you.

**Comment by xxyxxyxyx1** [comment]
Does anyone have a recommendation for sorting and using an `-X / -x` argument together? Sometimes I would like the files to be sorted before they are sent to the other program.

**Comment by rien333** [comment]
If the final program in the chain accepts a list of files as input (which a lot of unix tools to do) you may be able to get away with something like this instead (at least in fish shell):

```fish
# find all mp3s, sort them, and then call another program (e.g. du) on this sorted list
du -h (fd -emp3 | ... # your sorting routine here)
```

Or a much more ugly approach:

```fish
du -h (ls -t (fd -emp3))
```

The above gives you a list of  mp3s with their respective size, sorted by their modification date. 

I think doing this within a single `fd` command would involve implementing some kind of pre-sorting mechanism/flag, which may well be out of scope.

**Comment by tmccombs** [comment]
You can pipe to sort, then pipe that result to xargs

**Comment by zw963** [comment]
I thought the solution is quite clear. ( i use eza instead of ls for ls)

fd 'Screenshot (F|f)rom.*.png' ~/Pictures/ -X eza -s modified -1 --no-quotes

**Comment by sergeevabc** [comment]
> @zw963
> I thought the solution is quite clear. ( i use eza instead of ls for ls)

No, [eza][1] is a bad solution. Why? Because it is written in Rust language and Rust-based apps do not work on Windows 7 today and will not work on Windows 10 tomorrow. Why? Because Rust developers betrayed the community and decided go along with Microsoft decisions about what is good and what is bad for the masses.

![Image](https://github.com/user-attachments/assets/f88f103d-2155-44d3-82e9-58f4829ee182)

As you probably know, Microsoft, being an IT-capitalist, cares of its profit first, so they periodically release the new OS version and stop supporting the previous one, calling it “old and unsafe” (see [fearmongering](https://en.wikipedia.org/wiki/Fearmongering)). There is no need for the new version, but that is how they earn money to sustain their empire (see [artificial obsolescence][2]).

The truth is Windows 7 is stable, predictable and polished enough, that's why it does not require updates on a constant basis. It works and delivers, can you believe it? Just like a solid hammer in the garage I inherited from my deceased father — it continues to properly nail things even though its warranty has expired a long time ago.

Eza could be called a suitable solution if it were written, for example, in C(++), since apps in that language are still perfectly compiled for legacy operating systems. Famous examples are 7-zip, ffmpeg, imagemagick, xxhash, zpaqfranz, zstd. Alas, they do not provide the way to sort results piped from other apps.

Modern programmers (in particular, Rust ones) have forgotten that a solution is better to be made _future-proof_, so that it can be used around the globe (and not only in rich cities) for at least a decade without wasting time and money on dubious upgrades. Some Rust-based calculator can no longer be compiled to add 2 plus 2 until you have Windows 3000, a CPU with AVX and a fan glowing in the colors of the rainbow flag. Progress, huh?

Back to FD, it still sucks because it has no internal way of sorting results. And besides, FD is also written in Rust, so the current version [10.2.0][3] (August 2024) is probably the last one that works on Windows 7. This makes me sad, because I grew up believing that the spread of computers would help ease the human burden.

[1]:  https://github.com/eza-community/eza
[2]: https://en.wikipedia.org/wiki/Planned_obsolescence
[3]: https://github.com/sharkdp/fd/releases/tag/v10.2.0

**Comment by zw963** [comment]
After do a research on the stat, if we want order all files in one directory recursively, following command work.

```bash
 ╰──➤ $ fd -tf -g "*.cr" -X stat --format="%Y %y %n" |sort
1732251799 2024-11-22 13:03:19.000000000 +0800 ./spec/specs/process_spec.cr
1732281159 2024-11-22 21:12:39.229525190 +0800 ./spec/specs/procfile_option_spec.cr
1732281159 2024-11-22 21:12:39.229525190 +0800 ./src/procodile/commands/console_command.cr
1732683180 2024-11-27 12:53:00.010662240 +0800 ./spec/spec_helper.cr
1732683180 2024-11-27 12:53:00.010662240 +0800 ./spec/specs/app_determination_spec.cr
1732683180 2024-11-27 12:53:00.010662240 +0800 ./spec/specs/config_spec.cr
1741154153 2025-03-05 13:55:53.510999262 +0800 ./src/procodile/signal_handler.cr
1741154175 2025-03-05 13:56:15.243310930 +0800 ./src/procodile/commands/run_command.cr
1741228558 2025-03-06 10:35:58.557639991 +0800 ./src/procodile/commands/help_command.cr
1741229039 2025-03-06 10:43:59.786776180 +0800 ./src/procodile/app_determination.cr
1741229039 2025-03-06 10:43:59.786776180 +0800 ./src/procodile/commands/check_concurrency_command.cr
1741229039 2025-03-06 10:43:59.786776180 +0800 ./src/procodile/commands/exec_command.cr
1741229039 2025-03-06 10:43:59.786776180 +0800 ./src/procodile/commands/kill_command.cr
1741229039 2025-03-06 10:43:59.786776180 +0800 ./src/procodile/control_server.cr
1741229039 2025-03-06 10:43:59.786776180 +0800 ./src/procodile/core_ext/process.cr
1741229039 2025-03-06 10:43:59.790776311 +0800 ./src/procodile/logger.cr
1741229181 2025-03-06 10:46:21.469571739 +0800 ./src/procodile/commands/start_command.cr
1741229181 2025-03-06 10:46:21.469571739 +0800 ./src/procodile/start_supervisor.cr
1741230063 2025-03-06 11:01:03.220035831 +0800 ./src/procodile/commands/stop_command.cr
1741233167 2025-03-06 11:52:47.076374959 +0800 ./src/procodile/control_client.cr
1741234754 2025-03-06 12:19:14.282498779 +0800 ./src/procodile/control_session.cr
1741252393 2025-03-06 17:13:13.254812595 +0800 ./src/procodile/commands/restart_command.cr
1741254287 2025-03-06 17:44:47.387318576 +0800 ./src/procodile/commands/status_command.cr
1741324474 2025-03-07 13:14:34.597194204 +0800 ./1.cr
1741334341 2025-03-07 15:59:01.361443997 +0800 ./src/procodile/commands/log_command.cr
1741334341 2025-03-07 15:59:01.361443997 +0800 ./src/requires.cr
1741335433 2025-03-07 16:17:13.528468722 +0800 ./spec/specs/cli_spec.cr
1741344099 2025-03-07 18:41:39.450904639 +0800 ./src/procodile.cr
1741344241 2025-03-07 18:44:01.154192805 +0800 ./src/procodile/config.cr
1741344523 2025-03-07 18:48:43.181558599 +0800 ./src/procodile/supervisor.cr
1741344613 2025-03-07 18:50:13.680087547 +0800 ./src/procodile/instance.cr
1741344666 2025-03-07 18:51:06.365587583 +0800 ./src/procodile/cli.cr
1741344689 2025-03-07 18:51:29.406249338 +0800 ./src/procodile/process.cr
```

**Comment by aniketgm** [comment]
Sorry for the words, but this is B\*\*LS\*\*T -- Not adding a "sort" option or something similar that could work on Windows as well.
Someone suggested to add GNU utils `ls`. Well now hardly anyone uses CMD, almost all use powershell and powershell already has the `ls` command, which may conflict with the GNU `ls`.
however, nonetheless, I was able to get it working with the following (I use FZF, to further enhance functionalities)
```pwsh
# Get-Children is globally aliased by core PS as 'ls'
Get-ChildItem (fd -t f -e md) | Sort-Object CreationTime -Descending | Select-Object Name | fzf
```
This felt like an overkill, since `Get-ChildItem` already has `filter` and `recurse` option (though a bit slow), which I later switched to. But again, if anyone wants to use `fd` with some more complex options and sort it on Windows, this might work.

**_EDIT:_** Ok so I found another way, which involves using "eza". eza is available on Windows and I installed it using scoop.
And someone above mentioned to use fd's `-X` option with ls -- `fd pattern path -X ls -ltr`, which with eza becomes -- `fd pattern path -X eza -lr -s modified`. Don't put quotes around eza command.

**Comment by gzusseat** [comment]
> **_EDIT:_** Ok so I found another way, which involves using "eza". eza is available on Windows and I installed it using scoop. And someone above mentioned to use fd's `-X` option with ls -- `fd pattern path -X ls -ltr`, which with eza becomes -- `fd pattern path -X eza -lr -s modified`. Don't put quotes around eza command.

eza is useless if you want the full path though (without more convoluted pipes) . AFAIK

**Comment by GladioFeng** [comment]
The command `fd -tf -td -X eza -s modified -d` resolves my issue effectively.

**Comment by Paciupa** [comment]
I'm writing this comment because I've faced with this issue several times working on Windows. So I'll try to provide more information to help.

> but you can also choose not to have the -l flag and use platform specific tools with -X

> Does anyone have a recommendation for sorting and using an -X / -x argument together? Sometimes I would like the files to be sorted before they are sent to the other program.

The thing is that the OS mechanism used for `-x` / `-X` on Windows is [CreateProcess](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessw) / [ShellExecute](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/axe/shellexecute). It looks for a binary in `$PATH` and no shell is involved (In `ShellExecute`, the shell means [Windows Shell](https://en.wikipedia.org/wiki/Windows_shell), GUI). This is why it works for `fd foo -X bat` or `fd -H -I -a -g '.git' $someDir -x smerge --background '{//}'` because `bat` and `smerge` are binaries. However `ls` and `sort` are aliases and `Get-ChildItem` `Sort-Object` are cmdlets. Therefore, `fd foo -X ls` or `fd foo -X  Sort-Object` don't work in `PowerShell`, but `fd foo -X ls` works in `Git Bash`, where `ls` is a binary.

Because of that, I use `-X` when possible (like `fd foo -X bat -pP`) and pipes when it's not (like `fd foo | ls | sort LastWriteTime`, which is a shorter form of `fd foo | Get-ChildItem | Sort-Object -Property LastWriteTime`).

However, I'd appreciate it if `fd` would have a `--sort[r]` option like `rg` does (`rg --sortr modified 'foo'`).

> What's wrong with installing GNU's ls? If a system can acquire and install `fd`, wouldn't it be fairly easy to also install some GNU (compatible) tools?

- It's not clear how they would interfere with existing tools: aliases, etc.?
- How would they work in Windows world: paths, permissions?
- I already have a lot of features in pwsh and .NET.
 
But it's it worth mentioning that Microsoft recently [introduced](https://blogs.windows.com/windowsdeveloper/2026/06/02/build-2026-furthering-windows-as-the-trusted-platform-for-development/) their [fork](https://github.com/microsoft/coreutils) of [uutils ](https://uutils.org/).
