### ISSUE TITLE
fd should ignore .git when --hidden is on

### ISSUE THREAD

**Issue by amosbird** [sharkdp/fd#204]
`fd '' --hidden` searches files inside `.git/` without specifying `-I` or `--no-ignore-vcs`.

**Comment by sharkdp** [comment]
Why do you think `.git` (a hidden folder) should not be searched in the case where `--hidden` (= search hidden files and directories) is activated?

The `-I`/`--no-ignore` and `--no-ignore-vcs` options only affect directories and files which are targeted by entries in various `.gitignore` files and `.git` is usually not explicitly ignored (and probably should not be).

**Comment by amosbird** [comment]
OH, ok. I thought `--no-ignore-vcs` is like `git ls-files` which doesn't list `.git`

**Comment by cs** [comment]
For future reference: Adding `**/.git/` to your repo's `.gitignore` file seems to work with `fd --hidden`.

**Comment by sharkdp** [comment]
Another way is to put `.git` into a `.fdignore` file (in the repository or on a higher level).

**Comment by cs** [comment]
@sharkdp You are right. `~/.fdignore` is a better choice, because it has to be setup only once instead of each repository.

**Comment by jiacai2050** [comment]
I found `fd` respect [xdg convention](https://github.com/sharkdp/fd/blob/334488cab7709787ac1a7a0c6bfd4d3fd13b0cf7/src/walk.rs#L85), so we can put `.git` in `~/.config/fd/ignore` to keep home dir clean.

**Comment by mattrussell-sonocent** [comment]
Just to share my experience - I alas just used `fd --hidden` + `sd` to corrupt my local `.git`, because I naively assumed that if the tool respected patterns in `.gitignore`, surely it would not be searching within `.git`. So this behaviour was a surprise for me!

Certainly, it's on me to understand and check what a tool is doing, of course - but I think my assumption wasn't unreasonable.

> Why do you think .git (a hidden folder) should not be searched in the case where --hidden (= search hidden files and directories) is activated?

I'd make the argument that they should not be searched for the same reason that hidden folders that match patterns in`.gitignore` are not searched. If `.gitignore` patterns takes precedence over `--hidden`, `.git` should too.
