### ISSUE TITLE
(Feature request) Support extensions with multiple suffixes

### ISSUE THREAD

**Issue by althonos** [sharkdp/fd#214]
Hi there,
currently, `fd` does not support extensions with multiple suffixes in them, like `tar.gz` and the like. Of course, one could simply run `fd tar.gz`, but unfortunately this will also find some other files (such as `*.tar.gz.sig`). The correct workaround would be `fd tar.gz\$`, which starts to get cumbersome !

I could probably have a look at the code myself, since I don't think this should be too complicated to implement, but I'd like to have your opinion about it.

**Comment by sharkdp** [comment]
I would have actually needed this just yesterday. Completely agreed, this would be nice to have.

I think it's not *completely* trivial to implement this because we currently extract the extension via 
[`Path::extension`](https://doc.rust-lang.org/stable/std/path/struct.Path.html#method.extension) - which just extracts everything after the final `.` - and match that against the pattern. I guess we would have to resort to something like [`str::ends_with`](https://doc.rust-lang.org/stable/std/primitive.str.html#method.ends_with).

**Comment by sharkdp** [comment]
Closed via #215.
