### ISSUE TITLE
should --exclude allow for negating pattern?

### ISSUE THREAD

**Issue by franco** [sharkdp/fd#264]
I'm new to `fd` and maybe I am overlooking something. From my understanding `--exclude` should take precedence over patterns defined in `.gitignore`. Can I somehow "unignore" a pattern from the command line which was ignored in`.gitignore`? `.gitignore` allows a pattern to be negated by prefixing it with "!". I think `--exclude` should behave the same. Btw the following works (I assume because `.ignore` gets parsed after `.gitignore`:

.gitignore:
```
file1
file2
```

.ignore
```
!file1
```

=> `fd` will not ignore `file1` in this case.

**Comment by sharkdp** [comment]
Yes, that would be nice!

I tried to implement this a few days ago because I was looking for the same feature, but it's not straightforward because I'm afraid we cannot use the `Override` method of the `ignore` crate.

As you also found out, using `.ignore` files (or `.fdignore` files, starting with the next release) is a possible workaround.

**Comment by lpommers** [comment]
Do you know if there has been any progress on this? It is also a feature I am very interested in using. 

I also haven't been able to get a workaround working with a `.fdignore` file.

**Comment by sharkdp** [comment]
> Do you know if there has been any progress on this?

I don't think so.

> I also haven't been able to get a workaround working with a .fdignore file.

It works for me:

```
▶ touch file1 file2 file3
▶ echo "file1\nfile2" > .gitignore
▶ fd file
file3
▶ echo '!file2' > .fdignore
▶ fd file
file2
file3
```

**Comment by lpommers** [comment]
Thanks. I was able to repro this and get it working correctly when trying "unexclude" a single file like in your example. But I wasn't able to get it working with a sub directory structure.

`.gitignore`
```
my_directory
```

`.fdignore`
```
!my_directory/sub_dir
```

**Comment by sharkdp** [comment]
No, this will not work because `fd` will not descend into the `my_directory` folder at all.

What you could do would be to add something like this to your `.fdignore`:
```bash
# Do not ignore my_directory ...
!my_directory

# ... but everything below it ...
my_directory/*

# ... except for 'sub_dir'
!my_directory/sub_dir
```

I think I'm going to close this ticket for now, as I don't see any way to support this with the current version of the `ignore` crate - sorry! Please use the workaround and set things up in `.fdignore` files.
