### ISSUE TITLE
Executing vim with fd causes freeze

### ISSUE THREAD

**Issue by kenan-rhoton** [sharkdp/fd#265]
Terminal hangs with a simple search and execute:

`fd .clj src/ -x vim {}`

Which works perfectly with **find**:

`find src/ -name '*.clj' -exec vim {} +`

However, other commands (like `cat`) work correctly with `fd`, any ideas?

**Comment by sharkdp** [comment]
This is due to the parallel execution strategy of fd. `fd -x cmd` runs `cmd` for all search results in parallel and waits for each command to finish completely until the output is printed to the console. This does not work for interactive commands like `vim` because they will not finish without user input.

@mmstick Do you see any way we could make this work? Without introducing additional flags? Maybe just for `fd --threads 1`?

A (hacky) workaround is to spawn a non-terminal process:
```
> fd .xlj src/ -x gvim
```
(note that you can leave out the `{}`)

**Comment by sharkdp** [comment]
Unfortunately, I don't know how to fix this at the moment. Note that you can use
```
find src/ -name '*.clj' | xargs vim
```

to achieve the same thing (actually, this will open all files in a single vim instance, which might even be preferred - if not, you can also use `xargs -n1 vim`).
