### ISSUE TITLE
-E glob about "*.d" and ".emacs.d"

### ISSUE THREAD

**Issue by ShuguangSun** [sharkdp/fd#278]
I have question.
There is a directory ".emacs.d" in my $HOME, and I run fd in my $HOME
```
fd -E "*.d" -c never -i -t f -H -e el -p
```
which I want to find all elisp files (`*.el`) in $HOME, but don' want `*.d`. 
However, the -E glob `*.d` will exclude `.emacs.d` as well. 

The command line can do the search:
```
fd . .emacs.d -E "*.d" -c never -i -t f -H -e el -p
```

My question is that whether there is way to exclude files with extension "d"?

**Comment by sharkdp** [comment]
> My question is that whether there is way to exclude files with extension "d"?

If you really only want to ignore *files* with the `.d` extension, than you don't need `-E "*.d"` at all, because you are already searching for a particular file extension (`*.el`).

If, instead, you also want to exclude *directories* with the `.d` extension, you could create a `.fdignore` file in your HOME directory where you would explicitly whitelist `.emacs.d`:
```
*.d
!.emacs.d
```

Also, just a couple of things about your `fd` queries:
* `-p` should not be needed if you search for `*.el` files.
* `-i` should not be needed -- `--extension`/`-e` is case-insensitive anyway
* The `fd . .emacs.d ..` query is fine, but it will only search the `.emacs.d` folder (`.` is the regular expression). If you want to search both the current folder `.` and `.emacs.d`, you would have to do: `fd '' . .emacs.d`.

**Comment by ShuguangSun** [comment]
Thank you very much for the explaination.
