### ISSUE TITLE
Slow inside VirtualBox shared folder

### ISSUE THREAD

**Issue by gitpy** [sharkdp/fd#30]
This might be a rare use case. But fd is 5x slower then find on a VirtualBox shared folder for me.
For the same data set fd is faster native. Also inside Virtualbox normal (non-shared) folder fd is faster.

**Comment by sharkdp** [comment]
I'm not that familiar with VirtualBox. Do you know what makes these shared folders different? Do you run `fd` from within the VirtualBox?

**Comment by gitpy** [comment]
I forgot to mention that the host is a windows machine. Yes I ran `fd` inside VirtualBox but only inside shared folders the performance drops. They are pseudo-network redirectors (Windows Technology). My guess is, the way they get cached by the OS slows them down. Do you use a different access pattern then find?

**Comment by sharkdp** [comment]
I'm not sure. How did you perform these benchmarks? In particular, if there is any kind of caching going on, did you run an initial "warm-up" run?

**Comment by gitpy** [comment]
I ran the tests from the README with a warm-up and multiple runs.

I'm also testing on a bigger data set now, where the slowdown is only 2x. (8 seconds to 4 seconds)

When I find time I will test the `walkdir` crate itself to see if the behavior persists.

**Comment by sharkdp** [comment]
Ok, thank you

**Comment by sharkdp** [comment]
@gitpy I'm closing this for now, as (1) I'm not sure how to reproduce this and (2) the internals of `fd` have changed quite a lot since you opened this ticket: directories are now traversed in parallel.

If you are still interested, it'd be great if you could re-run your benchmark and see if this is still an issue. Feel free to re-open this ticket, if this is the case.

Anyways, thanks for your feedback!
