### ISSUE TITLE
Option to include current directory

### ISSUE THREAD

**Issue by cup** [sharkdp/fd#364]
The find tool includes the current directory:

~~~
$ find /var -maxdepth 1
/var
/var/cache
/var/lib
/var/log
/var/run
/var/tmp

$ cd /var
$ find -maxdepth 1
.
./cache
./lib
./log
./run
./tmp
~~~

and the ls tool has an option for it:

~~~
$ ls -a /var
.  ..  cache  lib  log  run  tmp

$ cd /var
$ ls -a
.  ..  cache  lib  log  run  tmp
~~~

**Comment by tmccombs** [comment]
Pedantic: the "-a" option for ls also shows the parent directory ".." and includes hidden (dot) files.

**Comment by sharkdp** [comment]
Closing this, as there is no further feedback.

**Comment by cup** [comment]
@sharkdp apologies - i didnt realize feedback was needed

we already have `-H` to cover hidden items, so we only need to deal with `.` and
`..`

we could introduce an option `-A`, my preference would be that `-A` will list
`.` but not `..`, so that using `-A -H` would give you a `find` like output

please reopen - thank you

**Comment by sharkdp** [comment]
Ok. Could you please tell us what your use case is?

**Comment by cup** [comment]
@sharkdp seeing how both `find` and `ls` have been able to output `.` for... several decades, i dont think i need to justify this. if that means you need to close again so be it.

**Comment by tmccombs** [comment]
Just because another program does something a certain way, doesn't necessarily mean it is valuable. Adding functionality just because that's the way find does it seems like wasted effort to me. Personally I have never needed find or ls to include the current directory, and have sometimes had to exclude it when piping it to another command. 

Have you found that functionality useful? If so, for what kind of things?

**Comment by cup** [comment]
@tmccombs you are right

honestly i cant remember the reason why i wanted it

it was right around the time that i was rewriting a script and considering `fd` over `ls`, but couldnt use `fd` because of reason in the OP - i will look back and try to jog my memory

**Comment by cup** [comment]
@sharkdp I remembered my use case - ok with find say you can to operate on a subtree, you can do this:

~~~sh
$ find gamma
gamma
gamma/delta
gamma/epsilon.txt
~~~

and then

~~~sh
find gamma -exec SOMETHING
~~~

and it will operate on everything **including gamma** - but FD cant do this, see:

~~~sh
$ fd --search-path gamma
gamma\delta
gamma\epsilon.txt
~~~

so can we reopen or WONTFIX this issue?

**Comment by sharkdp** [comment]
Sorry to be insistent here: what is `SOMETHING` in this case? What kind of command do you apply to every file *and directory*? Thinks like `chmod` and `chown` have `-R` arguments.

**Comment by cup** [comment]
@sharkdp i would really rather not divulge, as i dont want this issue to be pigeonholed or judged on just the basis of whatever specific example i give, as i feel strongly that this is a general and valid issue however one use case might be:

~~~
find gamma -exec touch {} +
~~~

again this isnt a great example but i dont think original issue should be judged on a specific example

**Comment by sharkdp** [comment]
Ok, let's keep this open for a while and try to get some other opinions.

**Comment by tmccombs** [comment]
@miguno I think you are seeing something else. Probably, `./crawl` is ignored by your .gitignore file? (See https://github.com/sharkdp/fd#troubleshooting). `fd` _does_ include files in the current working directory. What this issue is about is including the current working directory in the output. So in your example, including a "." line in the output (or /prefix-path/crawl/crawl-ref/source if using the `--absolute-path` option)

**Comment by miguno** [comment]
@tmccombs: Doh, you are totally right. It was indeed a `.gitignore` file! Sorry for necroing this thread for the wrong reasons.

**Comment by SFToro** [comment]
My use case is the following:
In a make file I can use find to tell my target that it depends on the contents of a given directory:
filename.jar: $(shell find PATH)

Using find also returns the parent directory. If a file is removed, the parent directory modification date changes and it is the only way to account for removed files.

If I use fd:
filename.jar: $(shell fd  -t d -t f . PATH)

I get the nested folders individually but not the the parent (for the case a file is deleted in the "root" of PATH. Do you know a workaround in order to show the parent folder?

**Comment by tavianator** [comment]
I think the easiest workaround is something like

```make
filename.jar: PATH $(shell fd . PATH)
```

i.e. just listing PATH explicitly as a prerequisite.  (Personally I would just use `find` in a Makefile as it's more portable.)

**Comment by 2ax3ax5** [comment]
As a user, I find weird that fd doesn't have an option for including the current directory.

**Comment by mahdi739** [comment]
Hi. My use case is that I want to perform a global file search using fzf. I would like to set its default command as follows:

For searching across drives:
```
$env:FZF_DEFAULT_COMMAND = 'fd . C:\ D:\ E:\ -u'
```
Additionally, I want to include the drive letters themselves in the search results.
Alternatively, I want to specify specific folders as the source:
```
$env:FZF_DEFAULT_COMMAND = 'fd . $env:UserProfile\Downloads "D:\IDM Downloads" -u'
```
In this case, I also want to include the source folders in the result list so that I can choose them as the paste destination, for example.

**Comment by rieje** [comment]
My use case (for including target in results) is this example to remove all empty directories recursively. Correct me if I'm wrong but there's no equivalent to this `find` command:

    find . -name testdir -type d -empty -delete

With `fd`:

    fd -t e -t d  testdir -X rmdir '{}'
     
`testdir` itself is not removed.

`target=testdir; fd -t e -t d . "$target" -X rmdir {} "$target"` only removes `testdir` if there are results.

I'm curious of a workaround that is relatively simple and doesn't involved calling `rmdir` more than once.

P.S. Unrelated, but n my attempt above, I was also thinking that exit codes to reflect whether or not there are results would be be useful. `fd -q` is not compatible with `-x`, `-X`. Again, workarounds like `fd . . -X printf '%s\n' {} | wc -l` involves unnecessarily calling external commands.

**Comment by karimknaebel** [comment]
> Sorry to be insistent here: what is `SOMETHING` in this case? What kind of command do you apply to _every file and directory_ within a given directory? Thinks like `chmod` and `chown` have `-R` arguments.

I have the same use case. I'm using `fd` since `chmod -R path` is much slower 2-3x than `fd . path -x chmod`.

**Comment by pmojabi** [comment]
Hello. I've started using `fd` instead of `find -exec` or even `find | parallel` because I found the performances to be better, but I was quite surprised to see that by default the parent directory is not included.
For sysadmin tasks, I frequently have to change permissions on large amount of files, and "chmod/chown -R" or other commands executed recursively are neither fast or selective enough.

For example I used to do :
```
find /path/to/directory/ -not -type l -print0 | parallel -0 -j32 'nfs4_setfacl -s A:fdg:NAMED_GROUP1:RX,A:fdg:NAMED_GROUP2:RWX,A:fd:OWNER@:RWX,A:fdg:GROUP@:RWX,A:fd:EVERYONE@:tncy {}'
```
So I would like to be able to do :
```
fd . -j 32 --unrestricted --type f --type d /path/to/directory/ --exec nfs4_setfacl -s A:fdg:NAMED_GROUP1:RX,A:fdg:NAMED_GROUP2:RWX,A:fd:OWNER@:RWX,A:fdg:GROUP@:RX,A:fd:EVERYONE@:tncy {}
```
And it works great, _except_ for the parent directory because it's not included in the search.

**Comment by tmccombs** [comment]
You could just run the chown for the "parent directory" separately.

**Comment by pmojabi** [comment]
I understand, but whenever I want to run chown+nfs4_setfacl+chmod on an entire file tree, it can become quite tedious if I need to duplicate each command because fd doesn't include the parent directory.

For example this :
```
{ 
dir="/mnt/foo";
subdir="bar";
acl_cmd="nfs4_setfacl -s A:fdg:LDAP_FOO_${subdir^^}:RWX,A:fd:OWNER@:RWX,A:fdg:GROUP@:RWX,A:fd:EVERYONE@:tncy";
time fd . -u -td -tf $dir/$subdir --exec bash -c 'chown :LDAP_FOO_${subdir^^} {}; $acl_cmd {}';
chown :LDAP_FOO_${subdir^^} $dir/$subdir;
$acl_cmd $dir/$subdir;
time fd . -u -td $dir/$subdir --exec chmod g+s {};
chmod g+s $dir/$subdir;
} &
```
could have been for example :
```
{ 
dir="/mnt/foo";
subdir="bar";
acl_cmd="nfs4_setfacl -s A:fdg:LDAP_FOO_${subdir^^}:RWX,A:fd:OWNER@:RWX,A:fdg:GROUP@:RWX,A:fd:EVERYONE@:tncy";
time fd . --parent -u -td -tf $dir/$subdir --exec bash -c 'chown :LDAP_FOO_${subdir^^} {}; $acl_cmd {}';
time fd . --parent -u -td $dir/$subdir --exec chmod g+s {};
} &
```
Personally I would have loved if this was the default behavior, not requiring a "--parent" option.
Then the --min-depth 1 option could be used to get the current behavior, just like with POSIX find.
But I understand this could be a breaking change and also that fd does not aim to reproduce the exact behavior of find.
