### ISSUE TITLE
Not performing as expected.

### ISSUE THREAD

**Issue by businessBoris** [sharkdp/fd#403]
Weird one, this one.

$ find ~/ -name blur*
/home/name/.local/share/data/Flavio Tordini/Musique/files/blur
/home/name/Documents/BPM/blur-emails-2018-01-10T22_51_07.976Z.csv
/home/name/Documents/BPM/blur-emails-2019-02-04T20_48_18.052Z.csv
/home/name/Downloads/blur-emails-2015-10-26T19_48_48.674Z.csv
/home/name/Downloads/blur-emails-2016-08-15T07_14_13.633Z.csv
/home/name/Downloads/blur-emails-2016-08-25T21_58_04.770Z.csv
$ fd blur ~/
$ fd blur* ~/
/home/name/SyncThing/othername/bluetooth

- Fedora 29 standard fd version is 7.0.0; have tried rawhide 7.2.0 version too.
- Is there a control file I'm missing?
- fs is btrfs (you can tell I'm clutching at straws!)
- Have tried quoting and escaping too.

Just to be clear: although there was a COPR (compile it yourself) article about fd, this is an official package from the standard repo.

**Comment by sharkdp** [comment]
Please read the Troubleshooting part of the README: https://github.com/sharkdp/fd#troubleshooting

Also, always quote patterns like "blur*". Otherwise, you get unexpected behavior when there are files starting with "blur" in the current directory (as your shell will expand the wildcard!).

And finally, `fd blur*` or `fd "blur*"` does not do the same as `find … -name "blur*"`. `fd` uses regular expressions by default (see https://github.com/sharkdp/fd#troubleshooting). So if you are searching for "blur*", you are asking for files that contain the string "blu", followed by zero or more "r"s. That's why `fd` finds the file named `bluetooth`.

**Comment by businessBoris** [comment]
So why wouldn't
`fd blur ~/ `
return the correct files?

**Comment by businessBoris** [comment]
I'm still confused. I don't think it is your program as it's too basic a problem - it's definitely my fault.

**Comment by sharkdp** [comment]
If something is still unclear, please ask.
