### ISSUE TITLE
Exclude glob pattern doesn't catch files with newline in name

### ISSUE THREAD

**Issue by rockandska** [sharkdp/fd#424]
Hi,

```
$ fd --version
fd 7.3.0
$ shopt -s extglob
$ cd /tmp
$ mkdir testfd
$ cd testfd
$ touch bob.mp3
$ mkdir a/
$ touch a/'a song'$'\n''with newline.mp3'                         
$ fd
a
a/a song
with newline.mp3
bob.mp3
$ fd -E *.@([ao]|so|mp3)                 
a
a/a song
with newline.mp3
```

**Comment by sharkdp** [comment]
I think you are misunderstanding something here.

The `--exclude`/`-E` option does not take a list of files (which is what you get after the shell expands your glob pattern), but a glob pattern itself - which almost always be escaped. So this works as expected:
```bash
fd -E '*.mp3'
```

You can not use extended globs, but you can add multiple globs:
``` bash
fd -E '*.a' -E '*.o' -E '*.so' -E '*.mp3'
```

**Comment by rockandska** [comment]
Indeed, thanks for the clarification  (always forgot the shell expansion itself, sorry....)
Not related with the issue, but the new line is print as is, compare to find who print it "more correctly"

```
$ touch 'a song'$'\n''with newline.mp3'
$ fd
a song
with newline.mp3
$ find
.
./a song?with newline.mp3
```
Regards,

**Comment by sharkdp** [comment]
I currently don't feel a strong need to "fix" this.

- When piping to other tools, the `-0` option can be used to separate results by NULL character (instead of newlines). 
- Replacing a potential newline character with some replacement like `?` does not really help much, in my opinion. It would also also be an additional operation that would have some performance impact.
- Personal opinion: I hope that no-one (actively) uses paths with newlines. I think it is a mistake that this is even allowed.
