### ISSUE TITLE
Display directories with trailing slashes

### ISSUE THREAD

**Issue by rockandska** [sharkdp/fd#436]
HI,

It will be great if there will be a possibility to have directories displayed with a trailing "/" (as an option or not).
When you don't use colors, there is no way to distinct directories from files.

Regards,

**Comment by sharkdp** [comment]
Thank you for the feedback.

I don't think there is any precedent for this (`ls` or `find`). I'd rather not add a trailing slash to directory names.

**Comment by tavianator** [comment]
There is precedent in `ls -p`

**Comment by sharkdp** [comment]
> There is precedent in `ls -p`

Thanks, I didn't know that.

My main point is that I'd rather not add a command-line option for something minor like this, as I really strive to keep the CLI small. So the question becomes: Do we want to add a trailing slash by default? (I'd rather not). If we don't, should there be some other way to make this possible (e.g. a more generic `--output-format` option)? I currently don't see the need for this.

Silly workaround :smile::
```
fd … -x ls -p
```

**Comment by rockandska** [comment]
In my opinion, if `fd` should be an alternative to find (gnu?), it should be able to reproduce the same behaviour at the maximum :) and if you would like to add a trailing slash to directories with `find` (gnu) you could by chaining `-type` / `-printf`.
For example:
```
find . \( -type d -printf '%p/\n' -or -printf '%p\n' \)
```

And parsing `ls` ouput is indeed a silly workaround ^^

**Comment by sharkdp** [comment]
> And parsing `ls` ouput is indeed a silly workaround ^^

`fd … -x ls -p` does not parse the output of `ls`. It executes `ls -p` for every search result and directly shows the `ls` output. It's not a great solution because it spawns a subprocess for every search result. But it works perfectly fine.

Arguably, using `find . \( -type d -printf '%p/\n' -or -printf '%p\n' \)` is worse. It's not only much longer to type, it can also not be used as an `alias` (I believe), because you can not simply append filtering criteria like `-name '…'`.

> In my opinion, if `fd` should be an alternative to find (gnu?), it should be able to reproduce the same behaviour at the maximum :)

I'm assuming you mean *"… at the minimum"*.

The very first paragraph in the README explicitly says: *"fd […] does not seek to mirror all of find's powerful functionality […]"*. So no, even if `find` would support this out of the box, we are not necessarily aiming to support this as well.

**Comment by sharkdp** [comment]
I'd like to close this. Let me know if there is anything left that should be discussed.

**Comment by blueForestIcarus** [comment]
"tar -tf" shows trailing slashes
I'm trying to diff the contents of my tar with the contents of a directory, but only common files
```
tar -f backup.tar --diff --directory mydir -T common.list
```
If common.list contains folders, they must have a trailing slash, otherwise tar will complain "./dir Not found in archive"
Without the trailing slash, the output of fd is actually _missing information_, there is no good way to add the trailing slash without checking the filesystem again to see what is a dir and what isn't.

**Comment by tmccombs** [comment]
Another workaround:

```
fd -t d -X printf "%s/\n" '{}' & fd -t f -t l 
```
(although, I think that might miss non-regular, non-link files)

**Comment by sharkdp** [comment]
> In most scripting use cases, controlling whether you get the trailing slash is important. It is pretty easy to delete the trailing slash with regex, but there is no good way to add the trailing slash without checking the filesystem again to see what is a dir and what isn't.

If you are not sure if something is a file or a directory.. you probably also don't care if it has a trailing slash or not. It's not like you can append to the path, for example. Because it could be a file.

It would be great if you could describe a real world use case where you would find the trailing slash useful. I would suspect that most use cases actually lead to a `--type=directory`/`-td` search where all results are directories anyways.



> Without the trailing slash, the output of fd is actually _missing information_, there is no good way to add the trailing slash without checking the filesystem again to see what is a dir and what isn't.

True. But as I pointed out above, so do most other programs. That's not necessarily a good reason, but I guess it shows that there aren't too many use cases that would require a trailing slash.

**Comment by sersorrel** [comment]
fwiw, a real-world use case I've literally just come up with is a script that post-processes the output of fd to add [links](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda); obviously it's easy to just take a whole line and transform it into a link, but it would be nice if, for files, I could make the directory-name part of the line link to the directory (e.g. to open in a file manager), and the filename part link directly to the file. As things stand, files and directories are differentiated by colour, but not by anything else, so I'd have to either rely on parsing the colour escape sequences (fraught, since they come from `$LS_COLORS`) or call stat() for every line of the output to work out whether it's a file or not.

Given that the difference between files and directories (and executables, symlinks, ...) are already illustrated with colour, it would be nice to make those differences accessible to scripts as well, like `ls -p` or `ls -F`.

(also, apart from anything else, I just _like_ seeing trailing slashes on directories? it makes them more visually distinct from files, so I have `ls -F` aliased to `ls` in my shell.)

**Comment by tmccombs** [comment]
I'm not saying this is a _good_ solution, but in a scripting environment, you could set `LS_COLORS` to something you know how to parse.

**Comment by sharkdp** [comment]
I'm going to reopen this. Please vote with :+1: (you would like to see trailing slashes for directories by default) and :-1: (you would rather not see trailing slashes) on this comment to indicate your preference. I think I'm inclined to add this to `fd` by default. I don't really see any drawbacks.

What I *would* vote against is having a new command line option for this.

**Comment by blueForestIcarus** [comment]
I think it is a good default, but changing it will definitely break things for people.

**Comment by sharkdp** [comment]
I'm not saying that it doesn't, but .. in which reasonable scenario would it really break things?

Another thing to worry about is the --exec commands.

**Comment by blueForestIcarus** [comment]
For an example. I currently have scripts comparing in which the output of `fd` is compared to the output of `tar -t` and I strip the trailing slashes from the tar output because fd currently doesn't print them.

Basically any situation where you compare fd's output to something else.

**Comment by sharkdp** [comment]
> Basically any situation where you compare fd's output to something else will have to be corrected.

Right. That's actually a good point.

**Comment by luukvbaal** [comment]
I'd very much like to see this added. Use case is to prepend icons with this iconlookup [script](https://github.com/luukvbaal/iconlookup) I wrote. Using the `-F` flag from `tree` and `ls` I'm able to distuingish directores, sockets, executables, doors and FIFO's as per `tree` manpage: 
`-F     Append a '/' for directories, a '=' for socket files, a '*' for executable  files,  a  '>' for doors (Solaris) and a '|' for FIFO's, as per ls -F`.

Would be great to see this functionality in `fd` for use in `fzf`.

**Comment by PatrickF1** [comment]
> I think I'm inclined to add this to fd by default. I don't really see any drawbacks. If anyone does, please write a comment.

Pro: helps identity directories if color is ever disabled
Con: IMO the / at the end is a bit ugly. What if the / was also colorized?

**Comment by sersorrel** [comment]
I feel that the trailing `/` should not be coloured, since e.g. `ls -F` colours the filename but not the `/`.

**Comment by sharkdp** [comment]
How about someone tries to implement this so we can see how it would look like? I think it shouldn't be too hard.

**Comment by sharkdp** [comment]
Adding this to the "fd 9" milestone. Which doesn't necessarily mean that we implement this. But I want to settle this question.

**Comment by yyogo** [comment]
Just thought of something: GNU ls has the `--indicator-style` flag:
```
‘--indicator-style=word’
    Append a character indicator with style word to entry names, as follows:
    ‘none’
        Do not append any character indicator; this is the default. 
    ‘slash’
        Append ‘/’ for directories. This is the same as the -p option. 
    ‘file-type’
        Append ‘/’ for directories, ‘@’ for symbolic links, ‘|’ for FIFOs, ‘=’ for sockets, and nothing for regular files. This is the same as the --file-type option. 
    ‘classify’
        Append ‘*’ for executable regular files, otherwise behave as for ‘file-type’. This is the same as the -F or --classify option. 
```
Maybe it would be better to add something similar instead of just the path separator?

**Comment by rishit-khandelwal** [comment]
Could i try working on this issue?

**Comment by yyogo** [comment]
@rishit-khandelwal there's already #812 (just for the trailing slashes, not `--indicator-style`, you can use it as a reference for that though)

**Comment by rishit-khandelwal** [comment]
So should i add `--indicator-style` instead?

**Comment by FilipeBento** [comment]
Hello, I am fairly new to github issues. I am just curious to know if this is under development right now. To be honest, my use case is different. When I use fd with fzf, I use the CTRL-T command which lists everything recursively, files and dirs. It's hard to distinguish files from dirs. the / at the end would be help greatly. I understand my use case is very specific. Let me know if this is going to be implemented or if you're aware of a workaround. Happy New Year! :)

**Comment by sharkdp** [comment]
This is being worked on in #812, as described above.

**Comment by FilipeBento** [comment]
Thank you for your response and your work, David.

**Comment by sharkdp** [comment]
closed in #812.

**Comment by chapmanjacobd** [comment]
the trailing slash looks nicer visually but it breaks the convention that both `find` **and** shell globbing use.

Thankfully, most programs don't care much about slashes--but this does make a significant difference to `rsync` and BSD `cp` where the trailing slash determines if the source directories are copied into the target folder or if it is merged into the target folder.

Here's another workaround

    function fd-bsd
        fd --exec-batch printf '%s\n' $argv
    end

**Comment by Piraty** [comment]
i just got bitten by the spurious trailing slash while piping fd's output into [xe](https://github.com/leahneuenkirchen/xe) (xargs replacenemt) to be used in  `rsync` cmdline  . very unexpected and slightly annoying.
my take would have been: if you need to know if a line represents a dir, test for it (`fd foo -x sh -c 'test -d "{}" && echo "is dir"'`) use `-t d` in the first place . instead of relying on trailing slash.
