### ISSUE TITLE
find all images and tar/zip

### ISSUE THREAD

**Issue by Lod3** [sharkdp/fd#489]
Hi,

I am trying to use fd to find all images in current directory and lower and zip or tar them in one command 

I tried multiple commands already. This one seems to work the best but the .tar is corrupt.
`sudo fd -t f "(jpg|png|gif)" -exec tar -rvf images.tar {} \;` 
`sudo fd -t f "(jpg|png|gif)" -x zip images.zip` does not work 
The -x switch worked before but with rm like so `fd -f t zi* -x rm -f`
How would I do this correctly?

**Comment by sharkdp** [comment]
You probably want to use the `-X`/`--exec-batch` option instead of `-x`/`--exec`.

Step by step:

1. Why do you use `sudo`? Is it really required?
2. Instead of `fd "(jpg|png|gif)"`, you can use `fd -e jpg -e png -e gif`, which would only find entries with jpg, png or gif as the actual file extension. Your pattern also finds files like `gifed.txt`.
3. You don't have to use `{}` or `\;`. `fd` will add that automatically.
4. Use `-X` instead of `-x` to run the command just once for all search results.

This should work:
``` bash
fd -tf -e jpg -e png -e gif -X tar cvf all-images.tar
```
or:
```
fd -tf -e jpg -e png -e gif -X zip all-images.zip
```

**Comment by Lod3** [comment]
> You probably want to use the -X/--exec-batch option instead of -x/--exec.
So that's what that meant, it wasn't clear from the man page, thanks.

> Why do you use sudo? Is it really required?
From where I am yes.

> Instead of fd "(jpg|png|gif)", you can use fd -e jpg -e png -e gif, which would only find entries with jpg, png or gif as the actual file extension. Your pattern also finds files like gifed.txt
Oh right, I did not know I could chain the filetypes like that.

> You don't have to use {} or \;. fd will add that automatically.
I was trying things to get it to work with other information I found. Doubt.

Would it be possible to add more examples to the man page maybe? 

Thank you, this will help alot.

**Comment by sharkdp** [comment]
Closing this, as there is no further feedback from @Lod3
