### ISSUE TITLE
Argument list too long

### ISSUE THREAD

**Issue by gpcr** [sharkdp/fd#494]
fd *.xls
-bash: /usr/bin/fd: Argument list too long
how to fix it?

**Comment by lespea** [comment]
You're basically using your shell to expand *.xls to all of the files ending in that and passing that to the fd program.  If you're looking for files with that extension you should use the e flag: `fd -e xls`.  Otherwise you'd want to do something like this (note: regex not glob syntax like you were using): `fd '\.xls'`

**Comment by sharkdp** [comment]
exactly... and if you want to use globs, you can use `fd -g '*.xls'`

**Comment by gpcr** [comment]
Thanks @lespea` fd -e xls and fd '\.xls$'` worked

@sharkdp ```
fd -g '*.xls'
error: Found argument '-g' which wasn't expected, or isn't valid in this context
```

**Comment by sharkdp** [comment]
`-g` is only supported in fd 7.4.0.
