### ISSUE TITLE
Request: only find text files

### ISSUE THREAD

**Issue by pakoito** [sharkdp/fd#532]
I'm trying to traverse a large repository to get metrics for file sizes. Doing operations like `grep -I` in `exec` shoots up the runtime excessively. Would it be possible to bake this behavior into the tool directly?

**Comment by sharkdp** [comment]
I'm not sure what you are asking. Could you go into a bit more detail what you want to do?

**Comment by pakoito** [comment]
Sure! I'm writing a daemon that counts all the lines in a directory. I can use `fd -t f -x wc -l \;` to count them, easily. Except! this is a large repository with files in multiple languages mixed with binary assets such as jpg files, and I don't have a list of vetted extensions. So what I'd like to do is traverse the respository only finding those files that are text.

The SO response to the problem is using `-x grep --binary-files=without-match -q -m1 \; -print` so it reads the first line of the file and filters those that aren't text files. So far so good.

The problem is that the grep operation increases the runtime tenfold. For a small repository whis wouldn't be a problem. For us it's the difference between minutes and hours :D

I was wondering if it'd be possible to add a filter option for non-binary files, the same way `--binary-files=without-match` (a.k.a. `-I`) does it for grep.

**Comment by sharkdp** [comment]
> Sure! I'm writing a daemon that counts all the lines in a directory. I can use `fd -t f -x wc -l \;` to count them, easily. Except! this is a large repository with files in multiple languages mixed with binary assets such as jpg files, and I don't have a list of vetted extensions. So what I'd like to do is traverse the respository only finding those files that are text.

It sounds like you want something like https://github.com/XAMPPRocky/tokei - would that fit your needs?

> The SO response to the problem is using `-x grep --binary-files=without-match -q -m1 \; -print` so it reads the first line of the file and filters those that aren't text files. So far so good.

That's a neat trick, but notice that `grep` only uses a heuristic to make the binary/text distinction. If someone is interested, I wrote an article on [*The difference between "binary" and "text" files*](https://dev.to/sharkdp/what-is-a-binary-file-2cf5) a while back. I would guess that `grep` actually reads more than one line, even when passing `-m/--max-count`, in order to employ its binary-detection heuristic.

> The problem is that the grep operation increases the runtime tenfold. For a small repository whis wouldn't be a problem. For us it's the difference between minutes and hours :D

My [`content_inspector`](https://github.com/sharkdp/content_inspector) crate includes a small program called `inspect` which uses the same heuristic as `grep` to detect binary files. It's 2.5x faster than `grep`, but that might be still too slow for your use case:

| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `fd -tf -x inspect` | 462.0 ± 7.2 | 453.3 | 478.8 | 1.00 |
| `fd -tf -x grep -I -q -m1 ""` | 1166.4 ± 8.8 | 1158.9 | 1189.1 | 2.52 ± 0.04 |

However, `inspect` can also run on a whole collection of files. So what works is something like the following (yes, it's a bit hacky):
```bash
fd -tf -X inspect | grep -v 'binary$' | cut -d: -f1 | xargs -d"\n" wc -l
```
It uses `fd`s `-X`/`--exec-batch` option to call `inspect` just once (note that some limitations currently apply, see #494). It then uses `grep -v` to reject all entries which were classified as binary. `cut` is used to select the file name. Finally, `wc -l` is called via `xargs` to process all arguments at once.

> I was wondering if it'd be possible to add a filter option for non-binary files, the same way `--binary-files=without-match` (a.k.a. `-I`) does for grep.

It's certainly possible and probably quite easy (using my `content_inspector` library mentioned above). However, I'm not yet convinced that this is something that we need to add to `fd`.

**Comment by pakoito** [comment]
Thank you for the advice, I will try to apply it!

**Comment by pakoito** [comment]
Even if I'd love to see this feature rolled into the main binary, I understand the problem is resolved. So let's close it for now :D

Thank you for all your hard work, keep it up!
