### ISSUE TITLE
find vs fd

### ISSUE THREAD

**Issue by blueray453** [sharkdp/fd#560]
I am trying to discover a better alternative to find  command.

fd seems nice and quite complete. However, the documentation says:

> While it does not seek to mirror all of find's powerful functionality, it provides sensible (opinionated) defaults for 80% of the use cases.

I am wondering what those missing 20% use cases are where I might need find. 

Can you please shed some light on this topic?

**Comment by sharkdp** [comment]
> I am wondering what those missing 20% use cases are where I might need find.

For me personally, `fd` can cover more like 99% of the use cases. This percentage has also increased over the last years since I wrote that statement. However, I still consider the statement to be an important design guideline of `fd`. We are not trying to solve every possible use case with `fd`.

Some things that are not possible with `fd` (this list is not exhaustive):

- Complex logic: that's probably the biggest point of all. You can not do something like this with `fd` (contrived example): *find files which have a `.py` extension OR (files which have a `.json` extension AND have been modified within the last two weeks)*
- `-mindepth` or `-depth`
- 100% "safe" way of deleting all search results (https://github.com/sharkdp/fd/pull/387)
- Very fine-grained file access time queries, like `-anewer`, `-atime`, etc.
- Finding by owner username/group/uid/gid (might be implemented at some point, see #307)

You can probably find much more by going through the `find` manpage.

Some tickets from the past:

- https://github.com/sharkdp/fd/issues/300: Reverse symlink lookup
- https://github.com/sharkdp/fd/issues/399: Support PCRE regular expressions for things like look-behind
- https://github.com/sharkdp/fd/issues/505: Is it possible to implement -lname?
- https://github.com/sharkdp/fd/issues/390: Complex use cases like `find . -mindepth 4 -maxdepth 4 \( -path '*foo/bar' -o -name '*ignore*' -o -path '*blah/etc*' \) -prune -o \( -perms 644 -o -perms 664 \) -name '*unicorn-sprinkles*' -exec cool-command-goes-here {} \;`

**Comment by data-man** [comment]
@sharkdp if you don't mind [fselect](https://github.com/jhspetersson/fselect) also is very good.

**Comment by blueray453** [comment]
> @sharkdp if you don't mind [fselect](https://github.com/jhspetersson/fselect) also is very good.

I use regprep, sd on a regular basis. So, I hope I will be much more comfortable with fd.

Moreover, the issues @sharkdp mentioned are almost non-issue to me (except the lookbehind thing). 

And one more crucial thing that is very important for me is the lead of the project. I already like him because, I asked him to tell me the flaws of his product and he told me without hesitation.
