### ISSUE TITLE
Consider other tools of the same category when defining default behavior

### ISSUE THREAD

**Issue by mversic** [sharkdp/fd#567]
This is not strictly an issue, rather a point of view I wanted to share on the `fd`s place in the world. From authors [comments](https://github.com/sharkdp/fd/issues/180#issuecomment-351605288) on other issues, I can see that our views converge

Please check out this [comment](https://github.com/BurntSushi/ripgrep/issues/178#issuecomment-613394664). In particular it is about `smart-case` default behavior in `fd` vs `rg` but paints a broader picture.

**Comment by sharkdp** [comment]
> I would say that next-generation CLI tools such as these two should converge on the same set of defaults unless a strong case can be made to have different behavior. Someone could argue that these two are not correlated, but I feel that there is a strong correlation between the two.

I definitely agree that the two tools are very much related. In `fd`, I tried very closely to follow what `rg` did before us. We named a lot of command-line options in the same way and even introduced a few ripgrep-compatibility options. 

But "smart-case by default" is not something that can be directly compared. ripgrep searches file contents while `fd` applies the pattern to file names.

I would argue that this alone justifies a different default. If you are searching a code base (via ripgrep), you probably care much more about a specific case than if you are searching a directory tree. You might want to search for types named `PointCloud`, but not for variables named `pointcloud`. On the other hand, most people do not have files called `pointcloud.h` AND `PointCloud.h` in the same project. For `fd`, I find myself very rarely reaching for `--case-sensitive` or `--ignore-case`. For `rg`, I actually use `alias rg="rg --smart-case"` because I am used to using smart-case, but I wouldn't recommend that ripgrep changes its default.

**Comment by mversic** [comment]
Ok, I don't disagree on the matter of `smart-case`. I just wanted to point this out so there wouldn't be much of unnecessary divergence between the two tools in the future. 

Frankly, it's great that most of `fd`s defaults are shared with `rg`, rather than being a drop-in replacement for `GNU find`. It's time to break some legacy :)
