### ISSUE TITLE
why --exec  and --max-results can't be used together?

### ISSUE THREAD

**Issue by rmNULL** [sharkdp/fd#623]
**What version of `fd` are you using?**
> fd 8.1.1

## Dummy example

$ `fd --max-results 4 -x true`
> error: The argument '--exec <cmd>' cannot be used with '--max-results <count>'
> ...

Posing it as a question, as the error is reported correctly.
A brief explanation on why this can't be done would be nice.

Thank You

**P.S**: i use fd on regular basis, thanks for this awesome tool :cake:

**Comment by sharkdp** [comment]
The main reason is: it has not yet been implemented.

However, I'm also not sure if we should. I'm afraid that it might be dangerous to provide this possibility. The problem is that the entries yielded by a `--max-results` search are not deterministic. If someone executes `fd --max-results 4 whatever` and then runs the same command again with `-x …` appended, the command would possibly be run for a different set of files.

Note that you can always pipe to `xargs`/`parallel` (possibly with the `-0` option for both commands) to achieve the same result.

**Comment by rmNULL** [comment]
> The problem is that the entries yielded by a --max-results search are not deterministic.

Oh, okay, that makes sense. Thanks for answering.

**Comment by danielkrajnik** [comment]
I assumed that this may be difficult to implement, but it would be really useful if it "became" possible at some point in the future. It would be great for testing
