### ISSUE TITLE
fd isn't really faster than find.

### ISSUE THREAD

**Issue by ftpd** [sharkdp/fd#628]
**Describe the bug you encountered:**

❯ time /usr/local/bin/fd --color never -HI . | tail -n 0
/usr/local/bin/fd --color never -HI .  0.47s user 1.11s system 225% cpu 0.703 total
tail -n 0  0.60s user 0.03s system 89% cpu 0.705 total
~
❯ time /usr/bin/find . | tail -n 0
/usr/bin/find .  0.08s user 0.60s system 70% cpu 0.968 total
tail -n 0  0.58s user 0.01s system 60% cpu 0.968 total

**Describe what you expected to happen:**

I expect fd to be faster ;-)

**What version of `fd` are you using?**

fd 8.1.1

**Which operating system / distribution are you on?**

Darwin 20.0.0 x86_64 (macOS 11 Big Sur beta2 - I had the same problem on 'stable' Catalina).

**Comment by sharkdp** [comment]
Hi, thank you for your report.

I see a total time of `0.703` seconds for fd and a time of `0.968` seconds for `find`. So `fd` is faster, right? Are you expecting it to be even faster?

Are you sure that you are taking care of caching effects in your "benchmark"? What happens if you run `fd` a couple of times? What if you run  `find` first, then `fd`?

If you want to run a proper warm-cache or cold-cache benchmark, please consider using `hyperfine` (see https://github.com/sharkdp/hyperfine#warmup-runs-and-preparation-commands).

What directory are you running this on? How can we reproduce this?

**Comment by lespea** [comment]
Furthermore I would say that you really aren't going to see massive differences unless it's big directories.  IMO the biggest advantage of fd over find is how clean the syntax is, ignoring a bunch of junk files by default, easily scoping to extensions, and proper regex support.  Speed is pretty far down the list since mostly it's io not cpu anyway.

**Comment by sharkdp** [comment]
The benchmark scripts are all public here: https://github.com/sharkdp/fd-benchmarks

Everybody is invited to run their own benchmarks. I personally see "massive differences" in runtime between `find` and `fd` for most benchmarks - even on moderately sized folders (10k files) where `find` takes 1 second or less. `fd` is typically 3 - 10 times faster.

What is true is that there won't be any significant gains on very small folders with ~10 files. Both programs are are so fast, however, that it hardly matters.

**Comment by ftpd** [comment]
It's my home, about 120k files, but right - I was looking just to 'user' value, not total.
