### ISSUE TITLE
Fd does not build inside termux on Android (aarch64) due to jemalloc usage

### ISSUE THREAD

**Issue by matu3ba** [sharkdp/fd#636]
**Describe the bug you encountered:**
fd fails to build on aarch64

**Describe what you expected to happen:**
jemalloc not being used, so the build does not crash

**What version of `fd` are you using?**

8.1.1

**Which operating system / distribution are you on?**
Unix: Linux 4.4.226-lineageos aarch64 and *no lsb_release* (Android)

Appended logfile.

What kind of performance boost does jemalloc offer? Do you plan on supporting Android-like platforms?

**Comment by matu3ba** [comment]
[err_install_fd.txt](https://github.com/sharkdp/fd/files/5011543/err_install_fd.txt)

**Comment by sharkdp** [comment]
> Do you plan on supporting Android-like platforms?

I'd be okay to merge changes if someone wants to work on that. Ideally, we should also add CI support for that platform. Otherwise we can not guarantee that things won't break in the future. I'm most probably not going to work on this myself.

> What kind of performance boost does jemalloc offer?

See this blog post: https://dev.to/sharkdp/an-unexpected-performance-regression-11ai

**Comment by sharkdp** [comment]
@matu3ba It would be great to get some feedback if the bug is fixed on `master`, thanks to the change by @fornwall.

**Comment by matu3ba** [comment]
@sharkdp This fixed the bug for me.
