### ISSUE TITLE
How to change the issued `fd` command so it will be faster than `find`?

### ISSUE THREAD

**Issue by 030** [sharkdp/fd#644]
**What version of `fd` are you using?**
fd 8.1.1

According to the documentation, `fd` is much faster than `find`. However in practice on our systems, there seems to be no difference. Perhaps we did not issue the right command? Outcome: 

```
time find /some/path -type f
```

```
time fd . '/some/path'
```

both take on average ~20s. How to change the `fd` command so that it will be significantly faster?

**Comment by sharkdp** [comment]
Thank you for your feedback. If you have read the README, you have probably also seen this section:

> Note: This is one particular benchmark on one particular machine. While I have performed quite a lot of different tests (and found consistent results), things might be different for you! I encourage everyone to try it out on their own. See this repository for all necessary scripts.

There is no guarantee that `fd` will be faster than `find`.

But please note that it's quite hard to do proper benchmarks. Simply running both commands in sequence using `time` will likely lead to wrong conclusions due to caching effects. See the README for further instructions on how to benchmark `fd`.

Do you really want to list all files in `/some/path`? If so, why don't you use `--type file`/`-tf` for `fd`, but for `find`?

Also, note that `fd` ignores hidden directories by default, `find` does not. `fd` respects `.gitgnore` files by default, `find` does not.

So you are comparing apples with oranges here.

Apart from that, can you give some details about your use case? How many results are listed (`fd … | wc -l`)? What kind of system are you on? What kind of file system?

If `fd` has to list a huge amount of files, it might be useful to use `--color=never` or to pipe the output to another program. You are probably not interested in scrolling through 1000s of results anyway.

**Comment by sharkdp** [comment]
@030  Any feedback?

**Comment by 030** [comment]
Thank you for the explanation. I tried your suggestions and it turned out that the bottleneck is Glusterfs in our environment.

**Comment by sharkdp** [comment]
Ok - thanks!
