### ISSUE TITLE
Include override for wstool (or other non-standard VCS)

### ISSUE THREAD

**Issue by rivertam** [sharkdp/fd#647]
We have a project that uses [wstool](http://wiki.ros.org/wstool), and the subdirectories are in the .gitignore. I don't see a way to say "for this directory only, include dir/subrepo1, dir/subrepo2, dir/subrepo3".

One solution would be to support [rosinstall](https://docs.ros.org/independent/api/rosinstall/html/rosinstall_usage.html), but that seems a bit esoteric for fd-find. I think a good middleground solution would be to have something like an `.fdinclude` directory, though that seems perhaps too specific to `fd`.

I'm not sure exactly what the feature should look like, but I would like `fd` to support this usecase of essentially ignoring lines of the gitignore.

**Comment by tmccombs** [comment]
I believe `.fdignore` has higher priority than `.gitignore`, and you can add inclusion rules to it by prefixing the rule with a `!`. It's basically like a rule that says "don't ignore this". Would that work for you?

For example, you could have a .fdignore like:

```
!dir/subrepo1
!dir/subrepo2
!dir/subrepo3
```

One limitation though is that you can't explicitly include a subdirectory of a directory that is ignored, since the parent directory won't even be recursed to begin with.

**Comment by rivertam** [comment]
This works for my usecase, thank you! I can see how others might be bothered by the caveat you include, but as this will work for any case I can think of to support wstool, I think this issue can be marked as closed.
