### ISSUE TITLE
Rename Subdirectories Using Pattern

### ISSUE THREAD

**Issue by blueray453** [sharkdp/fd#690]
**What version of `fd` are you using?**
fd 8.1.1

I am trying to rename the following directory structure 

```
Tests
├── Test1
│   ├── 2 - 1. Data
│   ├── 3 - 2. Data
│   ├── 4 - 3. Data
│   ├── 5 - 4. Data
│   ├── 6 - 5. Data
├── Test2
│   ├── 2 - 1. Data
│   ├── 3 - 2. Data
│   ├── 4 - 3. Data
│   ├── 5 - 4. Data
├── Test3
│   ├── 2 - 1. Data
│   ├── 3 - 2. Data
│   ├── 4 - 3. Data
│   ├── 5 - 4. Data
│   ├── 6 - 5. Data
```

With

```
Tests
├── Test1
│   ├── 1. Data
│   ├── 2. Data
│   ├── 3. Data
│   ├── 4. Data
│   ├── 5. Data
├── Test2
│   ├── 1. Data
│   ├── 2. Data
│   ├── 3. Data
│   ├── 4. Data
├── Test3
│   ├── 1. Data
│   ├── 2. Data
│   ├── 3. Data
│   ├── 4. Data
│   ├── 5. Data
```
If I run `fd -t d -x rename 's/^(\d+ -)\s(\d+.)/$1/'` in `Test1`, `Test2` & `Test3` - it works.

However, I want to use the command in `Test` so that I do not have to run the command in each directory. 

How can I do that?

**Comment by blueray453** [comment]
The command that is working is:

`find . -type d -execdir rename 's!^\./(\d+ -)\s(\d+\.)!$1!' {} +`

What is it's `fd` equivalent.

**Comment by sharkdp** [comment]
We don't have `-execdir` in `fd, but you can use `rename` from the top level directory if you match on the last `/` instead of `^`. You need to adjust your `fd` query to only match the directories that you want to be renamed. For example:
```bash
fd -t d --exact-depth 2 -x rename 's@/(\d+ -)\s(\d+.)@/$1@'
```
Alternatively, you can use an intermediate shell to switch the current working directory. For details, see #459

**Comment by blueray453** [comment]
Thank you very much.
