### ISSUE TITLE
remove leading and trailing whitespace from file and directory names recursively

### ISSUE THREAD

**Issue by blueray453** [sharkdp/fd#704]
**What version of `fd` are you using?**
fd 8.1.1

I can remove the trailing whitespace from file and directory names recursively using `fd ' *$' -x rename 's/ *$//' {} +`

However, when I try to remove leading whitespace from file and directory names recursively using `fd '^ *' -x rename 's/^ *//' {} +`, it does not work.

How can I do that?

**Comment by blueray453** [comment]
I just noticed if a directory has trailing whiltespace, and it contains a file which also has trailing whiltespace then, if I run `fd ' *$' -x rename 's/ *$//' {} +` once it only rename the directory. Then if I run the command again, it fix the file name. I mean I have to run the command twice.

**Comment by blueray453** [comment]
The [solution](https://unix.stackexchange.com/a/624083/206574) I found from stackoverflow is:

```
find . -depth ! -name . -exec rename -n '
  my ($dir, $base) = m{(.*)/(.*)}s;
  $base =~ s/^\s*//;
  $base =~ s/\s*$//;
  $_ = "$dir/$base";' {} +
```
How to replace `find` with `fd` in this case?

**Comment by sharkdp** [comment]
> I can remove the trailing whitespace from file and directory names recursively using `fd ' *$' -x rename 's/ *$//' {} +`

Just a few tips/comments:

* If you search for `' *$'`, you will find *every* file and directory, because the pattern says: "there should be zero or more whitespace characters at the end". I think what you want ist "one or more": `' +$'`.
* What is the trailing `+` for? That is not needed (or even wrong?). Maybe you saw that in the `find` syntax.
* Instead of using `-x`, you can use `-X` to execute `rename` just once.. with all search results. 
* There is a potential race condition here (which is what probably went wrong in some of your examples): if you have a file like `"foo    /bar.txt     "` where both the directory as well as the file have trailing whitespace, the `rename` command on the file can fail if the `rename` command of the directory finished first (because the file will not be available as `"foo    /bar.txt     "` anymore). There is a similar problem if you want to remove files/directories with `fd`. See this section: https://github.com/sharkdp/fd#deleting-files

What you can try:

Run it on directories first, then on files (this will still fail if there are directories within directories and all have trailing whitespace):
```
fd ' +$' -td -X rename 's/ +$//'
fd ' +$' -tf -X rename 's/ +$//'
```

> How to replace `find` with `fd` in this case?

We do not have an equivalen for `find -depth` (which traverses the file system in a depth first order). This does help with the race condition above. See also: discussion in #387

**Comment by blueray453** [comment]
Thank you very much.
