### ISSUE TITLE
fd -x lost color in the output

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [sharkdp/fd#718]
**What version of `fd` are you using?**
fd 8.2.1

The [bat utility](https://github.com/sharkdp/bat) can print the content of text file with highlighting. However when I invoke it through `fd`, it lost color in the output. An example command would be `fd toml -x bat {}`, which prints all `toml` file. This maybe not a `fd` issue, and I just want to bring this up and trying to find a solution. Thank.

**Comment by sharkdp** [comment]
`bat` auto-disables colors if it does not print to an interactive terminal (like many other tools, e.g. `ls`). You can force `bat` to print colors by using `bat --color=always`. By the way, the trailing `{}` is not needed:
```
fd toml -x bat --color=always
```
Another option is to use `fd`s `-X` (capital) option, which is similar to `-x`, but executes the command just once, with all search results as arguments (`cmd <file1> <file2> …` instead of `cmd <file1>`, `cmd <file2>`, …):
```
fd toml -X bat
```
This is how I usually combine `fd` and `bat` (see also: https://github.com/sharkdp/bat#find-or-fd). You don't need the `--color=always` in this case because `fd` directly sends the output to the terminal (for parallel execution with `-x`, we need to buffer it internally first).


I do actually wonder if we could solve this for `-x` as well. If `fd`s output goes to an interactive terminal, we could maybe fake being a TTY for the sake of `-x`.


If you use `fd -x`, the output is first written to an internal buffer (due to parallel execution).

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Thanks for the clarification.

**Comment by miguno** [comment]
I tried to run `clang-tidy` recursively on all `*.c` and `*.h` in a C project, for which I picked `fd`.  Switching from `-x` to `-X` did the trick to preserve the color output of `clang-tidy`.

```shell
$ fd -e h -e c -X clang-tidy {} -p build -- -isystem build/vcpkg_installed
```
