### ISSUE TITLE
How to properly use `-x`?

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [sharkdp/fd#767]
**What version of `fd` are you using?**
fd 8.2.1

What I want to do is find all jar files and use the utility `jstrings` to process them, then output the results to different files. For example, if I have two jar files `c:\temp\folder1\a.jar` and `c:\temp\folder2\b.jar`, the expected results are two files `c:\portapps\a.txt` and `c:\portapps\b.txt`. I tried this command: `fd jar -x jstrings {} >> "c:\portapps\{/}.txt"`, which generates the error *The system cannot find the path specified*. How can I make it work? Thanks.

**Comment by tmccombs** [comment]
I think the problem is that your command runs `fd jar -x jstrings {}` then writes the output to c:\portapps\{/}.txt. I'm guessing you meant to include the `>> "c:\portapps\{/}.txt"` in the command `fd` runs with `-x`. To do that you will need to dom something like `-x cmd.exe /c "jstrings {} >> c:\portapps\{/}.txt" `

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
> I think the problem is that your command runs `fd jar -x jstrings {}` then writes the output to c:\portapps{/}.txt. I'm guessing you meant to include the `>> "c:\portapps\{/}.txt"` in the command `fd` runs with `-x`. To do that you will need to dom something like `-x cmd.exe /c "jstrings {} >> c:\portapps\{/}.txt" `

Yes, that one works! Thanks for your explanation! I've written a PowerShell script to do it yesterday😄
