### ISSUE TITLE
find compatible mode

### ISSUE THREAD

**Issue by rdp** [sharkdp/fd#852]
It would be nice to have a "find" compatible mode option for the params, like a drop-in replacement...easier to adopt since one could just use it as an alias for the normal find command... :)

**Comment by tavianator** [comment]
This isn't likely to happen, since `find` is a very complicated utility to implement correctly and completely.  Can I ask why you want to replace `find` with `fd`?  Is it speed, colorization, or something else?

(Shameless self-promotion: if it's colors you want, I did write a drop-in replacement for `find`: https://github.com/tavianator/bfs.)

**Comment by rdp** [comment]
speed.  All I'd really want is some of the simpler features of find
(-name, -iname) to make it easier to...transition to? :)

**Comment by tmccombs** [comment]
perhaps you could write a script or shell function that translates the find options you care about into fd options?

For example `fd2 dir -name '*.png'` would become `fd -g '*.png' dir`.

**Comment by tavianator** [comment]
Just for fun I tried to do this on top of `bfs`'s parser.  The prototype is in the `find2fd` branch: https://github.com/tavianator/bfs/tree/find2fd

You can try it out like this:

```console
user@host $ git clone "https://github.com/tavianator/bfs"
user@host $ cd bfs
user@host $ git checkout find2fd
user@host $ make
user@host $ ./bin/find2fd ./src -name 'x*.c'
fd --no-ignore --hidden --glob --case-sensitive 'x*.c' './src'
```

The results should match*

```console
user@host $ fd --no-ignore --hidden --glob --case-sensitive 'x*.c' './src'
./src/xregex.c
./src/xspawn.c
./src/xtime.c
user@host $ find ./src -name 'x*.c'
./src/xspawn.c
./src/xtime.c
./src/xregex.c
```

\* with minor differences: `fd` never includes the search path itself in the results, regex syntax is different, etc.

I make no promises that the conversion is always correct.  But it tries to detect cases it can't handle:

```console
user@host $ ./bin/find2fd -exec echo \;
find2fd: error: ./bin/find2fd -exec echo ;
find2fd: error:               ~~~~~~~~~~~~
find2fd: error: fd doesn't support -exec without a placeholder.
user@host $ ./bin/find2fd -exec echo {} \;
fd --no-ignore --hidden --search-path '.' --exec 'echo'
```

I'm not going to spend any more time on this, but if it's useful to someone else, feel free to fork and maintain it.  The "right" way to implement this is probably as a separate script on top of `bfs -D tree`, which spits out a computer-friendly-ish parse tree:

```console
user@host $ bfs -D tree -name 'x*.c'
bfs: -D tree: bfs -P -S bfs -D tree . -color (-a (-name x*.c) (-print))
```

I'd be happy to make the necessary `bfs` changes to make that approach work correctly.  Mainly what's missing is a mode that dumps the parse tree and then stops without listing files.  Strings are also not escaped properly yet.

Closing this now, since the `fd` maintainers aren't likely to do any more work on this.  But if someone starts up a separate project for this, feel free to ping me (@tavianator).
