### ISSUE TITLE
--max-results=1 does not actually quit after the first result

### ISSUE THREAD

**Issue by durka** [sharkdp/fd#867]
**Describe the bug you encountered:**

I am running `fd` on a slow FUSE filesystem ([goofys](https://github.com/kahing/goofys)). It seems like `-1`/`--max-results=1` doesn't do what it says on the tin.

**Describe what you expected to happen:**

I expected `fd` to print the result and then quit. There is only one file on the path that matches my pattern.

I ran this command: `fd -F --max-results=1 PATTERN PATH`

One result is printed ~5 seconds later, but `fd` continues to run for a long time, at least a minute, until I interrupted it. FWIW, `find` can search the entire path in <25 seconds.

**What version of `fd` are you using?**

```
fd 8.2.1
```

**Which operating system / distribution are you on?**

```
Linux 5.8.0-63-generic x86_64
Distributor ID:	Ubuntu
Description:	Ubuntu 20.10
Release:	20.10
Codename:	groovy
```

**Comment by sharkdp** [comment]
Thank you for reporting this.

> I can reproduce this. I think you're right about the cause, we're still waiting for the worker threads to finish even once the receiver thread is done.

I don't think we are waiting for the workers threads to completely *finish* the search, but it might be the case that some of them keep running until … well to be honest, I don't know for sure. They will definitely quit once they attempt to send something back over the MPSC channel to the receiver thread (`SendError` / `send_result.is_err()`). But for details we would need to check the `WalkParallel` implementation in `ignore`. There seems to be a `is_quit` shortcut to stop some worker threads.



> I don't fully understand the purpose of this `wants_to_quit`, but could this be the fix?

`wants_to_quit` is only used for `Ctrl-C` detection. We shouldn't reuse it (otherwise we would quit with an error), but we could introduce a second atomic bool for that purpose. I don't really know how to easily reproduce this error (I tried by introducing some `thread::sleep` calls) though.

**Comment by tavianator** [comment]
The key to reproducing this is to search for something that has only one match  For example, I have only one file in my home directory called `title_t00.mkv`, and it is found reasonably early in the search.  But `fd title_t00.mkv ~ -1 -j1` takes a long time to finish.  I assume it's because nothing gets sent from the workers, so they don't see the closed channel.
