### ISSUE TITLE
-X option not work well with aliased command

### ISSUE THREAD

**Issue by erihsu** [sharkdp/fd#870]

**Comment by tmccombs** [comment]
could you provide some more details on what you mean by that. If you mean you can't use a shell alias as a command to run with `-X`, that's just a limitation of how aliases work. And you would either need to use the full command, use a wrapper script instead of an alias, run the alias using your shell (for example `bash -O expand_aliases my_alias`), or use a shell option to epxand the alias in the middle of commands instead of just at the beginning (for example `alias -g` in zsh).

**Comment by erihsu** [comment]
hi tmccombs
Thanks for your explaination. The problem I encountered is actually what you says. I am using `tcsh` and add some aliases in my  .cshrc. But I cannot use these aliases in the `-X` option. 
Full command actually works fine in `-X` option but I want to use more short command to invoke my program. And I dont find any alternative solution in `tcsh` to which you recommanded as in ` bash`.

**Comment by tmccombs** [comment]
I don't think there is much we can do here except maybe add documentation on why aliases don't work with `-X` and potential workarounds.
