### ISSUE TITLE
Next stable release

### ISSUE THREAD

**Issue by ImportTaste** [sharkdp/fd#882]
It's been a little while, almost a year since the last release, though there's been a lot of updates since then. Will it be soon?

**Comment by sharkdp** [comment]
Thank you for the reminder. I think that would be a good idea. I initially planned a few potentially breaking features for fd 9.x, but for now, we could certainly make a new 8.3 release, since we don't have any breaking changes so far: https://github.com/sharkdp/fd/blob/master/CHANGELOG.md#upcoming-release


I created a new milestone for a potential 8.3 release here: https://github.com/sharkdp/fd/milestone/10

@tmccombs @tavianator: What do you think? Are there some unresolved tickets or open PRs that you would like to see in that release, so I (we) could focus on them?

**Comment by tavianator** [comment]
Maybe a new `lscolors` release so we get https://github.com/sharkdp/lscolors/commit/dde45bfa6ca8a8540df6c431235287083e49a1b7

**Comment by sharkdp** [comment]
> Maybe a new `lscolors` release so we get [sharkdp/lscolors@dde45bf](https://github.com/sharkdp/lscolors/commit/dde45bfa6ca8a8540df6c431235287083e49a1b7)

:+1: done.

**Comment by tmccombs** [comment]
I'd kind of like https://github.com/sharkdp/fd/pull/861 to be merged as part of 8.3.

**Comment by sharkdp** [comment]
Agreed. It would be good to fix #760. Let's give this a proper final review. It looks quite close to being merge-able.

**Comment by sharkdp** [comment]
fd 8.3 has been released.
