### ISSUE TITLE
Is `fd -L -t l` supposed to work?

### ISSUE THREAD

**Issue by timkgh** [sharkdp/fd#939]
**What version of `fd` are you using?**
fd 8.3.1

I understand that the `-L` and `-t l` are kinda at odds with each other, but I would expect that `fd` could follow the symlinks and also print any symlinks it runs into. Is this a bug or desired behavior?

**Comment by timkgh** [comment]
It finds **broken** symlinks, which I suppose _could_ be useful 😄

**Comment by tmccombs** [comment]
I don't know if it is "supposed to work", but the reason it doesn't work is because of the way the [`walkdir`](https://github.com/BurntSushi/walkdir) crate works.

Specifically, if the option to follow symlinks is enabled, then [`metadata()`](https://docs.rs/walkdir/latest/walkdir/struct.DirEntry.html#method.metadata) method will return the metadata for the target of the symlink rather than the symlink itself. And most of the time, that is what you want, so that for example you can know if the symlink points to a file or a directory, or the modification time of the target of the symlink etc. 

Changing the behavior isn't too difficult. I almost have it working on a branch. But it seems to hang for some reason. I haven't figured it out yet.

**Comment by sharkdp** [comment]
I would like to close this for now. @timkgh See reasoning in #940.
